### ISSUE TITLE
chat messages printing twice

### ISSUE THREAD

**Issue by matt-seaton** [s4w3d0ff/python-poloniex#105]
I changed the code slightly.  It works but now every chat message gets printed twice, although the logging format is lost on the 2nd message.  Any ideas?

        
        from autobahn.asyncio.wamp import ApplicationSession, ApplicationRunner
        import logging, logging.handlers
        import sys
        from html import unescape
        
        
        logging.basicConfig(format='[%(asctime)s]%(message)s', datefmt="%H:%M:%S", level=logging.DEBUG)
        #trolllogger = logging.getLogger()
        #trolllogger.addHandler(logging.handlers.RotatingFileHandler('TrollBox.log', maxBytes=10 ** 9,
        #                                                            backupCount=5))  # makes 1Gb log files, 5 files max
        
        W = '\033[0m'  # white (normal)
        R = lambda text: '\033[31m' + text + W  # red
        G = lambda text: '\033[32m' + text + W  # green
        O = lambda text: '\033[33m' + text + W  # orange
        B = lambda text: '\033[34m' + text + W  # blue
        P = lambda text: '\033[35m' + text + W  # purp
        C = lambda text: '\033[36m' + text + W  # cyan
        GR = lambda text: '\033[37m' + text + W  # gray
        
        
        class Subscribe2Trollbox(ApplicationSession):
            async def onJoin(self, details):
                self.alter = True
                self.name = 'PulloutKing'
                self.mods = {
                    "Xoblort": 1,
                    "Chickenliver": 1,
                    "MobyDick": 1,
                    "cybiko123": 1,
                    "SweetJohnDee": 1,
                    "smallbit": 1,
                    "Wizwa": 1,
                    "OldManKidd": 1,
                    "Quantum": 1,
                    "busoni@poloniex": 1,
                    "Thoth": 1,
                    "wausboot": 1,
                    "Mirai": 1,
                    "qubix": 1,
                    "Oldgamejunk": 1,
                    "Chewpacabra": 1,
                    "j33hopper": 1,
                    "VenomGhost": 1,
                    "ultim8um": 1,
                    "TheDjentleman": 1,
                    "Bigolas": 1,
                    "Watchtower": 1
                }
                self.friends = []  # :.(
        
                def onTroll(*args):
                    try:
                        #logging.debug(args[0].upper(), str(args[1]))
                        name = args[2]
                        message = unescape(args[3])
                        # Name coloring
                        if name == self.name:  # own name is green
                            name = G(name)
                        elif name in self.friends:  # friends are purple
                            name = P(name)
                        elif name in self.mods:  # mods are orange
                            name = O(name)
                        else:
                            name = C(name)  # others are cyan
                        # Message Coloring
                        if self.name in message:  # mentions are green
                            message = G(message)
                        elif 'POLO TIP' in message:  # (supposed) polo tips are blue
                            message = B(message)
                        # other messages alternate from 'normal' to gray
                        elif self.alter:
                            message = GR(message)
                            self.alter = False
                        else:
                            message = message
                            self.alter = True
                        logging.info('%s(%s): %s' % (name, B(str(args[4])), message))
                    except IndexError:  # Sometimes its a banhammer!
                        # (u'trollboxMessage', 6943543, u'Banhammer', u'OldManKidd banned for 0 minutes by OldManKidd.')
                        logging.info('%s %s' % (R(name), R(message)))
        
                await self.subscribe(onTroll, 'trollbox')
        
        
        if __name__ == "__main__":
            subscriber = ApplicationRunner(u"wss://api.poloniex.com:443", u"realm1")
            subscriber.run(Subscribe2Trollbox)

**Comment by s4w3d0ff** [comment]
I'm not sure why it would output the message twice.. Can you paste a bit of the output here? It might help someone recognize where it is coming from. 

The push examples were thrown together using examples from here: https://github.com/crossbario/autobahn-python/tree/master/examples/ 
(wamp asyncio): https://github.com/crossbario/autobahn-python/tree/master/examples/asyncio/wamp

You could also try using https://github.com/absortium/poloniex-api/blob/master/poloniex/api/async.py#L89 if you think it will be more reliable. In the (possibly near) future that portion of absortium/poloniex-api might be added into this repo for convenance (or something like it).

**Comment by matt-seaton** [comment]
[20:18:14]scallywag(1044): VenomGhost, ok thanks
2017-05-01T20:18:14 scallywag(1044): VenomGhost, ok thanks
[20:18:15]danishhanif372(1): danishmuhammad570, I am! I am not selling, I think it will surpass btc soon when time will tell, I am sure you are of same opinion
2017-05-01T20:18:15 danishhanif372(1): danishmuhammad570, I am! I am not selling, I think it will surpass btc soon when time will tell, I am sure you are of same opinion
[20:18:18]LordKEK(96): sigwo: Got a strategy which works?  I managed to catch the A/D up-divergence on Kraken earlier.
2017-05-01T20:18:18 LordKEK(96): sigwo: Got a strategy which works?  I managed to catch the A/D up-divergence on Kraken earlier.
[20:18:19]Jingle0(71): what?... second guessing. No go ahead and dump your GNO load sir ;)
2017-05-01T20:18:19 Jingle0(71): what?... second guessing. No go ahead and dump your GNO load sir ;)
[20:18:19]ItsTheChamp(1): lmao at all these weak hands
2017-05-01T20:18:19 ItsTheChamp(1): lmao at all these weak hands


and so on....

**Comment by s4w3d0ff** [comment]
I'm not sure, it seems like 2 loggers are handling the same messages (maybe the wamp app?) Maybe instead of `logging.info()` you could try `trolllogger.info()` (after removing the comment from the `getLogger()` line) then change the loglevel of the `basicConfig` to `logging.INFO`
