### ISSUE TITLE
public TradeHistory method

### ISSUE THREAD

**Issue by evilive3000** [s4w3d0ff/python-poloniex#11]
import poloniex

    polo = poloniex.Poloniex()
    polo.timeout = 2

    data = polo.marketTradeHist('USDT_ETH', 1410158341, 1410499372)
    print(data)

throws:
`poloniex.py, line 214, in <lambda>` [#L214](https://github.com/s4w3d0ff/python-poloniex/blob/master/poloniex/poloniex.py#L214)
`NameError: name 'urlopen' is not defined`

**Comment by s4w3d0ff** [comment]
Ya, have yet to get around to updating that lambda since the switch to the requests module, which is why 'urlopen' is not defined. I am not sure if the 'polo.api()` method would work, (I don't think so).

I'll update the lambda asap.

**Comment by s4w3d0ff** [comment]
Updated, since poloniex has two 'returnTradeHistory' api commands (one private and one public) it has been a pain to write code around. Hopefully this will be a decent workaround.

**Comment by evilive3000** [comment]
thank you for quick fix

**Comment by s4w3d0ff** [comment]
No problem, thanks for the reminder, enjoy!
