### ISSUE TITLE
invalid JSON response from Poloniex is not parsed correctly

### ISSUE THREAD

**Issue by ethene** [s4w3d0ff/python-poloniex#111]
Hello,
sometimes the requests could not be completed correctly (may be due to DDOS or rate limit violation?), and apparently Poloniex responds with something that could not be parsed by your wrapper:

    balances = self.polo.returnAvailableAccountBalances()
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/site-packages/poloniex/__init__.py", line 449, in returnAvailableAccountBalances
    return self.__call__('returnAvailableAccountBalances')
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/site-packages/poloniex/retry.py", line 15, in wrapped
    return function(*args, **kwargs)
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/site-packages/poloniex/__init__.py", line 175, in __call__
    jsonout = _loads(ret.text, parse_float=str)
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Is it possible to wrap the json decoding into try/except and return the error with original text to aid troubleshooting?
Other solutions might be possible...

**Comment by s4w3d0ff** [comment]
I am fairly certain that this is a result of recent 'network issues' polo has been having. #109 seems to be related. These errors seem to show up only when poloniex is under 'heavy loads'.

**Comment by ethene** [comment]
I think the same error appears when you try to trade with insufficient balance, so it is better to wrap it anyway

**Comment by ekerstein** [comment]
I've been getting this error a lot lately too. Poloniex API seems to be very spotty. I've had to wrap it in try/except as you note.

**Comment by jencijanos** [comment]
poloniex return not a json object. in this time tradeHistory return '<Response [429]>'

**Comment by jencijanos** [comment]
poloniex return non json object only for some users. tested from digitalocean server, datacenter in NY -- no problem, last 6 hour work prerfect without error. from other ip (ukraine) >80% of calls return error

**Comment by jknielse** [comment]
For me this had been happening because of CloudFlare rate limiting. The issue was that this wrapper has a default timeout of 1s. If the poloniex interface is bogged down, then it can result in the library retrying several times, despite the fact that the poloniex servers are actually still working through the first request. The result is that CloudFlare thinks that you're maliciously calling their endpoints just for shits and giggles, and they ban your IP for a bit. When your IP is banned, CloudFlare will throw up an HTML response to let you know you've been rate limited, the poloniex library will try to parse it as JSON, and then you get this error.

Anyway, the fix: Set your timeout larger (I recommend 50s)

**Comment by cyzanfar** [comment]
@jknielse's solution works. You can find the timeout setting in the `Poloniex` constructor [here](https://github.com/s4w3d0ff/python-poloniex/blob/master/poloniex/__init__.py#L102)

**Comment by s4w3d0ff** [comment]
I think I am going to change it to 30 sec before merging. I am still getting lots of errors using 10 sec.

**Comment by cyzanfar** [comment]
Yeah I set it to 30 second and didn't have any issue yet

**Comment by ekerstein** [comment]
Could this be the cause of a buy order placing multiple times? I wrote a simple python script to place a buy order for me and I noticed it would often result in 2 or 3 buy orders placed milliseconds apart from each other. I'll try the new timeout and see if that helps.

**Comment by s4w3d0ff** [comment]
See: https://github.com/s4w3d0ff/python-poloniex/issues/109#issuecomment-302804256 if you haven't yet. Poloniex recommends 80 sec timeouts. It should help with duplicate requests and cloudflare bans.

**Comment by s4w3d0ff** [comment]
Invalid json responses are now captured and displayed as a `logging.ERROR` and 'PoloniexError()' is raised
https://github.com/s4w3d0ff/python-poloniex/blob/v0.4.5/poloniex/__init__.py#L249-#L251

Also, the default timeout parameter is now `None` which means it will wait forever for the response. See: 
http://docs.python-requests.org/en/master/user/advanced/#timeouts
https://github.com/s4w3d0ff/python-poloniex/blob/v0.4.5/poloniex/__init__.py#L106
