### ISSUE TITLE
Runned script not exit

### ISSUE THREAD

**Issue by AlleoNET** [s4w3d0ff/python-poloniex#112]
I have simple script.py:

```
from poloniex import Poloniex
polo = Poloniex()
polo.returnChartData('BTC_ETH', 1800, 1405699200, 9999999999)
```

running this via command: python script.py execution can't be finished.
So I must stop it manually Ctr+C.

**Comment by s4w3d0ff** [comment]
I think this is related to #109 #111 
Are you getting delay messages? It can take almost a full minute for the retry delay list to be exhausted and an error to be displayed if the request isn't reaching poloniex.

**Comment by AlleoNET** [comment]
Thank for reply. I use python3 so I swtiched to poloniex-api with asyncio and now works ok.

**Comment by s4w3d0ff** [comment]
This wrapper should work fine on python3 for the REST api. Like I said, it is probably just network issues...

**Comment by paikov** [comment]
I'm having the same problem. Left the script running over-night and it still hasn't exited. I'm using Python 3 on macOS 10.13.2.
