### ISSUE TITLE
returnTradeHistory being processed as private command

### ISSUE THREAD

**Issue by robobeaver6** [s4w3d0ff/python-poloniex#116]
I think there is a bug in returnTradeHistory() method.  I was getting [] return.  after stepping through I noticed that 'returnTradeHistory' appears in both PUBLIC_COMMANDS and PRIVATE_COMMANDS list.  I believe it is a public command, but was being processed by the private command conditional in the Poloniex class.  This was causing it to silently fail.

Removing line 69 in the __init__.py resolved the issue.

**Comment by s4w3d0ff** [comment]
Use `returnTradeHistory` for **private trade history**, use `marketTradeHist` for **public trade history**.

**Comment by robobeaver6** [comment]
Ah, OK.  The Polo API docs is misleading in this sense I guess, as it has both a public and private api call with the same name.
