### ISSUE TITLE
returnOrderBook

### ISSUE THREAD

**Issue by kuqadk3** [s4w3d0ff/python-poloniex#117]
Can we make it return more than 20 orders? (default is 20 orders)

**Comment by ekerstein** [comment]
returnOrderBook(self, currencyPair='all', depth=20):
        """ Returns the order book for a given market as well as a sequence
        number for use with the Push API and an indicator specifying whether the
        market is frozen. (defaults to 'all' markets, at a 'depth' of 20 orders)
        """

for example, try: returnOrderBook(currencyPair='all', depth=100)

**Comment by kuqadk3** [comment]
Solved.
Thanks you alot !
