### ISSUE TITLE
How do you place a market sell or buy order?

### ISSUE THREAD

**Issue by rjb25** [s4w3d0ff/python-poloniex#118]
I see the following code
```
def buy(self, currencyPair, rate, amount, orderType=False):
        """ Places a limit buy order in a given market. Required parameters are
        "currencyPair", "rate", and "amount". You may optionally set "orderType"
        to "fillOrKill", "immediateOrCancel" or "postOnly". A fill-or-kill order
        will either fill in its entirety or be completely aborted. An
        immediate-or-cancel order can be partially or completely filled, but
        any portion of the order that cannot be filled immediately will be
        canceled rather than left on the order book. A post-only order will
        only be placed if no portion of it fills immediately; this guarantees
        you will never pay the taker fee on any part of the order that fills.
        If successful, the method will return the order number. """
        args = {
            'currencyPair': str(currencyPair).upper(),
            'rate': str(rate),
            'amount': str(amount),
        }
        # order type specified?
        if orderType:
            possTypes = ['fillOrKill', 'immediateOrCancel', 'postOnly']
            # check type
            if not orderType in possTypes:
                raise PoloniexError('Invalid orderType')
            args[orderType] = 1

        return self.__call__('buy', args)
```
What do you pass it for market order which obviously would have no rate specified?

**Comment by ekerstein** [comment]
The way I solved this in my code is that for a market buy, I put the rate at 110% of the lowest ask (so you know it will execute), and for a market sell you put 90% of the highest bid (for the same reason).

These are two functions I wrote that allow you to just pass the currency pair and BTC amount to trade. It pulls the ticker to grab the ask/bid. It's a "fillorkill" to ensure that it only executes as a market order.

# Market buy in BTC
def buyMarket_inBTC(currencyPair, btcamount):
    ticker = public.returnTicker()
    rate = float(ticker[currencyPair]["lowestAsk"]) * 1.1 # Use lowest ask for market buy order
    amount = float(btcamount) / rate
    private.buy(currencyPair, rate, amount, orderType="fillOrKill")

# Market sell in BTC
def sellMarket_inBTC(currencyPair, btcamount):
    ticker = public.returnTicker()
    rate = float(ticker[currencyPair]["highestBid"]) * .9 # Use highest bid for market sell order
    amount = float(btcamount) / rate
    private.buy(currencyPair, rate, amount, orderType="fillOrKill")

**Comment by rjb25** [comment]
Thanks that clears things up.
