### ISSUE TITLE
returnOrderbook raises issues when depth isn't far enough

### ISSUE THREAD

**Issue by StarBruck** [s4w3d0ff/python-poloniex#119]
I noticed that in the __init__.py, the depth for returnOrderbook is only 20. Can you set this value somewhere higher like 200-300? I set mine to 500 and I noticed no difference in execution speed - this is on a 10 year old computer. When using a script to calculate statistics based off of the data returned from returnOrderbook, I run into errors because of the short depth. I released my script to many others, they would have to change the value manually - not all of them are tech savvy,

Thanks in advance.

**Comment by s4w3d0ff** [comment]
I don't really have a problem raising the default, but I can see i impacting other users using the default expecting `depth=20`.
