### ISSUE TITLE
loanbot errors

### ISSUE THREAD

**Issue by redlegoman** [s4w3d0ff/python-poloniex#120]
I know the loanbot.py script is only an example, but I'm rubbish at python and loanbot is just what I wanted. However, it gives an error intermittently:

> [14:30:06]Active Loans:-----------------------------
[14:30:06]2017-05-31 06:33:31|LTC:0.99999889-[rate:0.0007%]-[fees:0.00000202]
[14:30:06]2017-05-31 05:25:04|DOGE:16762.52933964-[rate:0.0007%]-[fees:0.03952270]
Exception in thread Thread-8 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 1073, in run
  File "/usr/lib/python2.7/threading.py", line 491, in release
  File "/usr/lib/python2.7/threading.py", line 384, in notify
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

Any idea what I can do to stop it?

**Comment by s4w3d0ff** [comment]
oops, didn't mean to close this.

I updated the loanbot in the master branch let me know if you are still getting errors, I didn't see any when I tested.

**Comment by redlegoman** [comment]
That seemed to do the trick, except now I get a new aerror after a few iterations. I'm not sure if it's the script or Poloniex themselve,  but I see this:

> PoloniexError: Nonce must be greater than 1496384941516182. You provided 1496384546554535.

**Comment by s4w3d0ff** [comment]
Usually, this will happen if you try to using an api key with different api wrappers, each api wrapper calculates the nonce a bit differently and poloniex expects the nonces to be sequential for each api key. 

If you use one wrapper and that wrapper has a 'larger' nonce, and then you change to another wrapper using the same api keys, and that new wrapper is generating a 'smaller' nonce, you will get this error.

To fix, you just have to generate a new api key(pair) on poloniex and use it in the new wrapper.

If you generate new keys and it is still showing this error let me know, it is then probably something wrong with this wrapper.

**Comment by s4w3d0ff** [comment]
or maybe 2 instances of the loanbot running at once?

**Comment by s4w3d0ff** [comment]
Im closing this, if nonce errors are still occuring please continue the conversation here: #125

**Comment by redlegoman** [comment]
Sorry, yes, I should have replied earlier. I generated a new API key just for the loanbot and all is ok.  Thanks for your help.
