### ISSUE TITLE
nonce must be greater...

### ISSUE THREAD

**Issue by ethene** [s4w3d0ff/python-poloniex#125]
Sometimes the message appears requiring a retry:

```
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/site-packages/poloniex/__init__.py", line 449, in returnAvailableAccountBalances
    return self.__call__('returnAvailableAccountBalances')
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/site-packages/poloniex/retry.py", line 15, in wrapped
    return function(*args, **kwargs)
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/site-packages/poloniex/__init__.py", line 182, in __call__
    raise PoloniexError(jsonout['error'])
poloniex.PoloniexError: Nonce must be greater than 1496733348197745. You provided 1496733348197661.
```

is is possible to adjust the nonce increase somehow? I believe it might happen because Polo is fighting DDOSes and might slow down some requests on the Cloudflare side

**Comment by s4w3d0ff** [comment]
You can try and set the nonce using:
`polo._nonce = #a bigger number`, but I don't understand how the nonce can be so far ahead, I could be wrong, but I thought the nonce is recalculated before `retry` attempts the call again. Have you tried setting `timeout=None`? I'm going to be away from the internet for a few days so I won't be able to do any testing/debugging/commits. 

I'm hoping this issue is something wrong on polos end.

**Comment by ethene** [comment]
Timeout is set to 130 (per latest Polo message suggestion, the default is also worth increasing but this is a different ticket)

just noticed in code:
self._nonce += 42

42 might be too small number to cover all the delays and DDOS protections, could you make it a separate parameter in the class constructor maybe?

**Comment by s4w3d0ff** [comment]
You can try to overwrite the nonce property:
```python
class Polo(Poloniex):  

    @property  
    def nonce(self):  
        self._nonce += 100  
        return self._nonce  

api = Polo()
```
Not sure if the above is formatted correctly, my tablet does not display markdown very well.

**Comment by ethene** [comment]
Investigating the behaviour I've found that this situation might be possible when several concurrent calls are sent to Polo. In that case, some calls with lower nonce might be slower, resulting in the issue.
Currently I am wrapping the code with a custom decorator to sync them

`

from threading import Lock

class synchronized(object):

    def __init__(self, *args):
        self.lock = Lock()

    def __call__(self, f):
        def lockedfunc(*args, **kwargs):
            try:
                self.lock.acquire()
                try:
                    return f(*args, **kwargs)
                except Exception as e:
                    raise e
            finally:
                self.lock.release()

        return lockedfunc`

**Comment by s4w3d0ff** [comment]
why does github keep closing issues I reference in pull requests? Annoying... anyway, I did not mean to close this.

Let me know if this helps, the slow nonce errors are now being captured and updating the nonce with whatever poloniex reports as the last nonce, then retrying. You might still have sync issues if the connections get slow but at least now the nonce gets updated.
