### ISSUE TITLE
mongoTicker.py doesn't return any values

### ISSUE THREAD

**Issue by hockeyadc** [s4w3d0ff/python-poloniex#126]
When I run mongodb.py, I receive

"    print("BTC_ETH: percentChange= %s" % ticker()['last'])
TypeError: 'NoneType' object has no attribute '__getitem__'"

Any ideas here?

**Comment by s4w3d0ff** [comment]
When I try the mongoTicker.py example I get the following error:

```
2017-06-13T11:47:06-0700 dropping connection to peer tcp4:104.20.13.48:443 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)
```
Since the WAMP application did not connect to the server, the ticker data isn't being updated. This is most likely the problem.

See #115

**Comment by hockeyadc** [comment]
I tried it again and added:

from` twisted.internet.ssl import CertificateOptions
options = CertificateOptions()
app_runner = ApplicationRunner(u"wss://api.poloniex.com:443", u"realm1", ssl=options)`

But now I get the error:
Traceback (most recent call last):
  File "D:/Users/live/PycharmProjects/PoloniexMongoDB/Poloniex to DB.py", line 107, in <module>
    print("USDT_BTC: last= %s" % ticker()['last'])
TypeError: 'NoneType' object is not subscriptable

**Comment by amorallife** [comment]
@hockeyadc do you have spaces in your python filename? formatting might be trying to subscript a non string data type... or the channel isn't able to be subscribed to - hard to tell which its saying

**Comment by s4w3d0ff** [comment]
see #195
