### ISSUE TITLE
historical data [question]

### ISSUE THREAD

**Issue by reteps** [s4w3d0ff/python-poloniex#129]
is there a way to get historical data or 24hr open price?

**Comment by s4w3d0ff** [comment]
`returnChartData` is probably what you want, if you want 24hr candles just:

```python
from poloniex import Poloniex
polo = Poloniex()
# this should give you all the historical candle data for BTC_LTC market in 24hr candles
polo.returnChartData('BTC_LTC', period=polo.DAY*24, start=0)
```

If you want something a bit more readable you can use pandas:

```python
from poloniex import Poloniex
import pandas as pd

api = Poloniex(jsonNums=float)

raw = api.returnChartData('BTC_LTC', period=api.DAY * 24, start=0)
df = pd.DataFrame(raw)

# adjust dates format and set dates as index
df['date'] = pd.to_datetime(df["date"], unit='s')
df.set_index('date', inplace=True)

# show the end of dataframe
print(df.tail())
```

And if you need to see a chart, take a look at #123

**Comment by techietrader** [comment]
Hi,
Is there a way to get hourly historical data?
Period=3600
??

**Comment by s4w3d0ff** [comment]
Available candle periods: 5min(300), 15min(900), 30min(1800), 2hr(7200), 4hr(14400), and 24hr(86400)

They don't provide hourly charts but 30 minute and 2 hour.

**Comment by s4w3d0ff** [comment]
There is a way to calculate the 1 hour period by combining the data from 2, 30min candles.

Example:
Say you have 10 candles of data, each candle representing 30 min period. If you take the 'open' price for the first candle, and the 'close' for the 2nd 30 min candle.
You now have your open and close price for your 1 hour candle. To get the highs and lows you just need the highest 'high' of the 2 candles and the lowest 'low'. Repeat for the rest of candles and you now have 5, 1 hour candles.

This works with any number of candles so if you want weekly candles you can combine every 7 candles into one.

**Comment by techietrader** [comment]
Yup... cool solution...

that should be easy

**Comment by techietrader** [comment]
Should we be using MultiThreading here?
- First thread runs every first half of the hour to store the OHLC data in say 'Data0' which can be a dict 
- Second thread which runs every hour to not only store the data for second half in a new dict ,say- 'Data1' but also combines it with 'Data0' and stores it in altogether a new Dict called 'Data' and also runs the actual analysis over it? 


Is there a easy way you suggest?

**Comment by s4w3d0ff** [comment]
I would start here: 
https://stackoverflow.com/questions/9944436/converting-ohlc-stock-data-into-a-different-timeframe-with-python-and-pandas#9968147

If you are using the latest  version of pandas you can use the `resample` method:
```python
from poloniex import Poloniex
import pandas as pd
from time import time

api = Poloniex(jsonNums=float)
# create dataframe of 30min candles
df = pd.DataFrame(api.returnChartData('BTC_LTC', period=1800, start=time()-api.MONTH))

# convert dates to datetime and set date as index
# the df.resample method requires datetimes as index
df['date'] = pd.to_datetime(df["date"], unit='s')
df.set_index('date', inplace=True)
print(df.tail())
```
```
                        close      high       low      open  quoteVolume  \
date                                                                       
2017-07-06 18:00:00  0.019739  0.019768  0.019625  0.019641  5439.709059   
2017-07-06 18:30:00  0.019715  0.019751  0.019660  0.019741  3891.407022   
2017-07-06 19:00:00  0.019650  0.019720  0.019580  0.019715  6341.164832   
2017-07-06 19:30:00  0.019528  0.019679  0.019452  0.019650  7325.047509   
2017-07-06 20:00:00  0.019545  0.019617  0.019477  0.019536  4680.334200   

                         volume  weightedAverage  
date                                              
2017-07-06 18:00:00  107.199816         0.019707  
2017-07-06 18:30:00   76.620544         0.019690  
2017-07-06 19:00:00  124.819123         0.019684  
2017-07-06 19:30:00  143.301738         0.019563  
2017-07-06 20:00:00   91.326223         0.019513  
```
```python
# define how the df is re-sampled
ohlc_dict = {
    'open': 'first',
    'high': 'max',
    'low': 'min',
    'close': 'last',
    'quoteVolume': 'sum',
    'volume': 'sum',
    'weightedAverage': 'mean'}

# resample the df
df = df.resample(rule='1H', closed='left', label='left').apply(ohlc_dict)
print(df.tail())
```
```
                         high     close       low      open      volume  \
date                                                                      
2017-07-06 16:00:00  0.019700  0.019600  0.019500  0.019550  413.192628   
2017-07-06 17:00:00  0.019730  0.019611  0.019594  0.019600  232.037304   
2017-07-06 18:00:00  0.019768  0.019715  0.019625  0.019641  183.820360   
2017-07-06 19:00:00  0.019720  0.019528  0.019452  0.019715  268.120861   
2017-07-06 20:00:00  0.019617  0.019545  0.019477  0.019536   91.326223   

                      quoteVolume  weightedAverage  
date                                                
2017-07-06 16:00:00  21103.341087         0.019578  
2017-07-06 17:00:00  11815.830713         0.019639  
2017-07-06 18:00:00   9331.116081         0.019698  
2017-07-06 19:00:00  13666.212341         0.019624  
2017-07-06 20:00:00   4680.334200         0.019513  
```
Using `rule='1H'` will combine the data to form 1 hour periods. ('2D' = 2 days, '1W' = 1 week)
See here for more info on re-sampling rules:
https://stackoverflow.com/questions/17001389/pandas-resample-documentation

**Comment by techietrader** [comment]
Thanks a lot.
That helped!!!

**Comment by Metaphor31** [comment]
Can someone help to create " UNIX timestamp " for the start here : 
raw = api.returnChartData('BTC_LTC', period=api.DAY, start=time()-api.YEAR*10)

I would like to be able to find equivalence between calssic dates and UNIX so that I can ask properly 
Thanks

**Comment by s4w3d0ff** [comment]
@Metaphor31 I am not sure what you are asking, I think you want to start the chart data from a specific date. This is what I use:

```python
from time import strptime, localtime, mktime
from calendar import timegm

def UTCstr2epoch(datestr, fmat="%Y-%m-%d %H:%M:%S"):
    """
    - takes UTC date string
    - returns epoch
    """
    return timegm(strptime(datestr, fmat))

def localstr2epoch(datestr, fmat="%Y-%m-%d %H:%M:%S"):
    """
    - takes localtimezone date string,
    - returns epoch
    """
    return mktime(strptime(datestr, fmat))


# >>> localstr2epoch("2017-04-01", fmat="%Y-%m-%d")
# 1491030000.0
```

```python
raw = api.returnChartData('BTC_LTC', period=api.DAY, start=localstr2epoch("2017-04-01", fmat="%Y-%m-%d"))
```

**Comment by Metaphor31** [comment]
@s4w3d0ff  Thank you so much !!! Amazing reply ! 
Yes indeed I want to start from a specific date and be able to switch from UNIX timestamp to classic_python_string_dates, 
I used something less expert than your solution : (I am going to try ti use yours)
Example : 
import arrow
start_date_pol="14/12/2013"
start_1_unix=arrow.get(start_date_pol).timestamp
raw1 = api.returnChartData('BTC_LTC', period=api.DAY, start=start_1_unix)
Remark : to switch back : 
bc = arrow.get(1293840000).datetime
print(bc.isoformat())

1 issue is that if I use : start_1="01/01/2014" I get the same start date as if I use : start_2="14/12/2013"
The output of the line raw1 = api.returnChartData('BTC_LTC', period=api.DAY, start=start_1_unix) is still the same date : 2014-01-18 just like if I can't get data previous to this date...

**Comment by s4w3d0ff** [comment]
Here are the other functions I use for timestamps (I used to keep them in this repo but they seemed 'out of place' so I removed them):

```python
from time import time, gmtime, strftime, strptime, localtime, mktime
from calendar import timegm

def epoch2UTCstr(timestamp=False, fmat="%Y-%m-%d %H:%M:%S"):
    """
    - takes epoch timestamp
    - returns UTC formated string
    """
    if not timestamp:
        timestamp = time()
    return strftime(fmat, gmtime(timestamp))


def UTCstr2epoch(datestr=False, fmat="%Y-%m-%d %H:%M:%S"):
    """
    - takes UTC date string
    - returns epoch
    """
    if not datestr:
        datestr = epoch2UTCstr()
    return timegm(strptime(datestr, fmat))


def epoch2localstr(timestamp=False, fmat="%Y-%m-%d %H:%M:%S"):
    """
    - takes epoch timestamp
    - returns localtimezone formated string
    """
    if not timestamp:
        timestamp = time()
    return strftime(fmat, localtime(timestamp))


def localstr2epoch(datestr=False, fmat="%Y-%m-%d %H:%M:%S"):
    """
    - takes localtimezone date string,
    - returns epoch
    """
    if not datestr:
        datestr = epoch2localstr()
    return mktime(strptime(datestr, fmat))
```

```
>>> tstamp = time()
>>> tstamp
1505230700.4179187
>>> epoch2localstr(tstamp)
'2017-09-12 08:38:20'
>>> epoch2localstr(tstamp, fmat="%Y/%m/%d")
'2017/09/12'
```

You can also use them to get the current time (without milliseconds):
```
>>> localstr2epoch()
1505231163.0
>>> UTCstr2epoch()
1505231164
>>> epoch2localstr()
'2017-09-12 08:48:24'
>>> epoch2UTCstr()
'2017-09-12 15:48:27'
```

**Comment by Metaphor31** [comment]
@s4w3d0ff Thank you so much for this amazing detailed answer :)

Do you know how to get the total list of all the pairs from the Poloniex website ? Maybe there is query or table that gives all the pairs like   'BTC_LTC' for all FX

thanks

**Comment by jacob-roth** [comment]
The list I have is:
```
USDT_ETH
ETH_ZRX
BTC_DCR
BTC_SYS
BTC_STEEM
BTC_ZEC
USDT_BTC
BTC_SBD
BTC_STRAT
BTC_NAV
BTC_PPC
XMR_DASH
BTC_REP
BTC_BCN
USDT_ETC
USDT_STR
ETH_LSK
BTC_XBC
BTC_BLK
ETH_GNT
BTC_RIC
BTC_FLO
BTC_NMC
USDT_DASH
BTC_AMP
ETH_STEEM
BTC_NOTE
USDT_REP
XMR_NXT
XMR_BLK
USDT_LTC
BTC_BCH
BTC_BTM
USDT_XMR
BTC_XRP
BTC_PASC
BTC_NXC
BTC_BTCD
BTC_XCP
ETH_BCH
BTC_BELA
BTC_SJCX
XMR_BCN
BTC_DGB
BTC_ARDR
USDT_BCH
BTC_PINK
BTC_DASH
BTC_BTS
BTC_GRC
BTC_MAID
XMR_BTCD
BTC_VRC
BTC_ETC
BTC_POT
BTC_XEM
BTC_XMR
BTC_STR
BTC_CLAM
BTC_NXT
BTC_ZRX
BTC_HUC
BTC_GNO
BTC_VIA
BTC_NAUT
BTC_EMC2
BTC_SC
XMR_MAID
BTC_DOGE
XMR_LTC
BTC_OMNI
BTC_NEOS
ETH_GNO
ETH_ZEC
ETH_ETC
USDT_NXT
XMR_ZEC
BTC_GNT
BTC_FCT
BTC_BURST
BTC_LBC
USDT_ZEC
BTC_LTC
BTC_XVC
BTC_ETH
USDT_XRP
BTC_LSK
BTC_BCY
BTC_GAME
BTC_XPM
BTC_FLDC
BTC_RADS
BTC_VTC
ETH_REP
BTC_EXP
```
which I got from requesting Ticker data.

**Comment by s4w3d0ff** [comment]
`api.returnCurrencies()` will give you all the individual currency info: https://poloniex.com/public?command=returnCurrencies

and `api.returnTicker` will give you the market pairs: https://poloniex.com/public?command=returnTicker

so you can do something like:
```python
pairs = [pair for pair in api.returnTicker()]
```
```
>>> pairs
['BTC_VRC', 'BTC_BTS', 'BTC_XCP', 'BTC_BCN', 'ETH_CVC', 'BTC_NXT', 'BTC_HUC', 'BTC_DASH', 'BTC_FLDC', 'USDT_XRP', 'ETH_ZEC', 'ETH_REP', 'BTC_ZEC', 'USDT_ETH', 'USDT_NXT', 'BTC_SYS', 'BTC_SBD', 'BTC_REP', 'BTC_GRC', 'BTC_XPM', 'ETH_BCH', 'BTC_AMP', 'BTC_RADS', 'BTC_SJCX', 'USDT_REP', 'BTC_OMG', 'BTC_ZRX', 'BTC_LSK', 'XMR_ZEC', 'BTC_GNO', 'BTC_BURST', 'ETH_LSK', 'XMR_LTC', 'BTC_NAUT', 'USDT_DASH', 'USDT_ETC', 'XMR_MAID', 'BTC_BTCD', 'BTC_FLO', 'BTC_XMR', 'BTC_XBC', 'BTC_LTC', 'XMR_NXT', 'ETH_GNO', 'USDT_BCH', 'BTC_XEM', 'BTC_VTC', 'BTC_MAID', 'USDT_STR', 'BTC_CLAM', 'BTC_ETH', 'BTC_XVC', 'BTC_BELA', 'BTC_GNT', 'BTC_STEEM', 'XMR_BTCD', 'BTC_BCY', 'BTC_PINK', 'BTC_CVC', 'BTC_DOGE', 'BTC_EXP', 'ETH_STEEM', 'BTC_ETC', 'BTC_STR', 'BTC_PPC', 'USDT_BTC', 'BTC_NMC', 'BTC_PASC', 'BTC_EMC2', 'BTC_BLK', 'USDT_LTC', 'BTC_SC', 'ETH_ZRX', 'BTC_DCR', 'BTC_ARDR', 'XMR_BLK', 'BTC_NEOS', 'BTC_FCT', 'ETH_OMG', 'BTC_NXC', 'ETH_GNT', 'BTC_DGB', 'BTC_LBC', 'XMR_BCN', 'BTC_XRP', 'BTC_STRAT', 'BTC_RIC', 'XMR_DASH', 'BTC_BTM', 'BTC_VIA', 'BTC_POT', 'BTC_GAME', 'USDT_XMR', 'BTC_BCH', 'BTC_NAV', 'BTC_OMNI', 'BTC_NOTE', 'ETH_ETC', 'USDT_ZEC']
```

**Comment by Metaphor31** [comment]
Thanks again, 

I have a question for the date I get when asking for data. I have the closing price and a date, I would like to know what is the exact time at which the price is taken during the day (for close) 
By using your code below, I can't get the minute or the information to know which local time is it. 
The idea behind is that if I get other data sets from other exchange I want to be sure that in history, on the same line for a closing date, the two prices from two different exchanges correspond to the same time, I mean in the same time zone

# Get time series 
raw_pro1 = api.returnChartData('BTC_LTC', period=api.DAY, start=start_date_pro)
df_pro = pd.DataFrame(raw_pro1)
df_pro["date"].ix[1,1]
df_pro['date'] = pd.to_datetime(df_pro["date"], unit='s')
df_pro.set_index('date', inplace=True)
df_pro.head # 2014-01-18 

Maybe my question has no answer because : 
" Unix time / POSIX time / Epoch time: It is a system for describing instants in time, defined as the number of seconds that have elapsed since 00:00:00 Coordinated Universal Time (UTC), Thursday, 1 January 1970, not counting leap seconds "
" UTC is not a time zone, but a time standard that is the basis for civil time and time zones worldwide. This means that no country or territory officially uses UTC as a local time."

So to solve the issue, maybe the only solution is to convert dates from all data sets from all exchanges in the same UNIX Time or check the type of date they use. 

Thanks in advance for your advice,

**Comment by s4w3d0ff** [comment]
Ya, double check what time format each exchange is using and you will probably want to convert them to UTC epochs. That way you can use the same functions to convert all the dates (from all exchanges) to the same timezone/format if you need to re-sample the data.

The problem with precision of dates might be the epochs poloniex returns with the chart data, it does not seem to have milliseconds:
```python
{
    'close': 0.014019,,, 
    'date': 1505505600.0, 
    'quoteVolume': 65866.18968589,,,
}
```
Even with 5 min candle periods:
```python
{
    'close': 0.01416989,,, 
    'date': 1505583600.0, 
    'weightedAverage': 0.01417079,,,
}
```
You could try to 're-sample' [(mentioned above)](https://github.com/s4w3d0ff/python-poloniex/issues/129#issuecomment-313511673) the chart data from both exchanges at a larger candle period (say you, retrieve 10min candle data from both exchanges then re-sample both to 30 min candle periods) and hope the dates line up.

You may need to play around with the `closed` and `label` params in resample in order to get the dates to line up:   
`df = df.resample(rule='1H', closed='left', label='left').apply(ohlc_dict)`

**Comment by Metaphor31** [comment]
Thank you very much, 
Just by curiosity, have you tried to build a code to get all data from https://www.cryptocompare.com/api/ ? 
Thanks

**Comment by s4w3d0ff** [comment]
Something like this?:
```python
try:
    from urllib import urlencode
# python 3
except:
    from urllib.parse import urlencode

def makeUrl(base='https://min-api.cryptocompare.com/data/histoday?', **kwargs):
    return base + urlencode(kwargs)

args = {
    'fsym': 'BTC',
    'tsym': 'USD',
    'limit': '100',
    'aggregate': '3',
    'e': 'Bitfinex'
}

url =  makeUrl(**args)
print(url)
```
```
https://min-api.cryptocompare.com/data/histoday?aggregate=3&e=Bitfinex&limit=100&tsym=USD&fsym=BTC
```

**Comment by Metaphor31** [comment]
Again this is an amazing answer! so easy to understand, the best 🥇  ! Thanks! 👍 I used it to create all the DF for all historical data for all pairs for all exchanges 👍 
This **kwargs thing is quite amzaing !!! https://stackoverflow.com/questions/1769403/understanding-kwargs-in-python

**Comment by MichelleMeng** [comment]
Hi, 
do you know why am I getting these errors?
TypeError: __init__() got an unexpected keyword argument 'jsonNums'
AttributeError: 'Poloniex' object has no attribute 'timer'
AttributeError: 'Poloniex' object has no attribute 'DAY'
Thank you!

**Comment by s4w3d0ff** [comment]
It is probably because you are using the pip "poloniex" package (which I don't maintain and is quite different from this repo)

Try uninstalling whatever package you have installed:
`pip uninstall poloniex`

Then install this repo:
`pip install git+https://github.com/s4w3d0ff/python-poloniex.git`
