### ISSUE TITLE
tickers do not appear to function

### ISSUE THREAD

**Issue by tunage** [s4w3d0ff/python-poloniex#140]
queuedTicker.py will output the last trade 1 time and then just repeat same 'last'.

I was unable to get any coin data out of any of the other 3 samples.
I edited the coin pair.

**Comment by s4w3d0ff** [comment]
The WAMP versions `queuedTicker.py` and `mongoTicker.py` will take some effort to get working, they were working fine when I first wrote them, but it seems poloniex has changed something in the way that they handle WAMP connections, see #115.

The `dumbTicker.py` should work as long as you have the correct dependencies installed:
```
pip install pandas pymongo
pip install git+https://github.com/s4w3d0ff/python-poloniex.git
```
You also need mongod (the [mongodb](https://docs.mongodb.com/manual/installation/) server) running on your machine.

Same goes for the `wsMongoTicker.py` example. You will need  [mongodb](https://docs.mongodb.com/manual/installation/) installed (and running) along with:
```
pip install pymongo websocket-client
pip install git+https://github.com/s4w3d0ff/python-poloniex.git
```

Right now the most reliable way to connect a websocket and collect 'real-time' ticker data is using the undocumented websocket api (that doesn't seem to comply with WAMP protocols and uses a different url).

The `wsMongoTicker.py` example uses the undocumented websocket api (soon to be api v2?) So, as long as the required modules are installed and mongod is running, it should work. Unless poloniex made more changes...

If you still can't get it to work please include a traceback.

**Comment by tunage** [comment]
dumbTicker is the one I am concentrating on the most because it is the most bare bones and close to what I need to accomplish.

Its not functioning correctly. It will show the last trade but never update the variable with fresh data.


session:
brads@brads-Dell ~/coinz/exchanges/poloniex/python-poloniex $ sudo pip3 install pandas pymongo
Requirement already satisfied: pandas in /usr/lib/python3/dist-packages
Requirement already satisfied: pymongo in /usr/local/lib/python3.5/dist-packages

run:
brads@brads-Dell ~/coinz/exchanges/poloniex/python-poloniex $ python3 examples/ticker/queuedTicker.py 
Starting ticker
TICKER: tickPitcher process started
Catching...
TICKER: tickCatcher thread started
0.10066001
2017-07-07T05:02:12-0600 dropping connection to peer tcp4:104.20.12.48:443 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)
0.10066001
0.10066001
0.10066001
0.10066001
0.10066001
0.10066001
0.10066001
^CTraceback (most recent call last):
  File "examples/ticker/queuedTicker.py", line 98, in <module>
2017-07-07T05:03:30-0600 Received SIGINT, shutting down.
    time.sleep(10)
KeyboardInterrupt
2017-07-07T05:03:30-0600 Main loop terminated.
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt


Your loop has a 10s timer, so that code ran close to 2 min. According to that output, not one sale occurred during execution???
the records on the URL reflect 100 transactions over the same time period.


code used:
brads@brads-Dell ~/coinz/exchanges/poloniex/python-poloniex $ cat examples/ticker/queuedTicker.py 
#!/usr/bin/python
# -*- coding: utf-8 -*-
from multiprocessing import Process, Queue
from multiprocessing.dummy import Process as Thread

from twisted.internet import reactor
from twisted.internet.defer import inlineCallbacks
from autobahn.twisted.wamp import ApplicationSession, ApplicationRunner

import poloniex

queue = Queue()


class TickPitcher(ApplicationSession):
    """ WAMP application """
    @inlineCallbacks
    def onJoin(self, details):
        yield self.subscribe(self.onTick, 'ticker')
        print('Subscribed to Ticker')

    def onTick(self, *tick):
        queue.put(tick)

    def onDisconnect(self):
        if reactor.running:
            reactor.stop()


class Ticker(object):

    def __init__(self):
        self.ticker = poloniex.Poloniex().returnTicker()
        self._appRunner = ApplicationRunner(
            u"wss://api.poloniex.com:443", u"realm1"
        )
        self._appProcess, self._tickThread = None, None
        self._running = False

    def __call__(self):
        return self.ticker

    def tickCatcher(self):
        print("Catching...")
        while self._running:
            try:
                tick = queue.get(timeout=1)
            except:
                continue
            else:
                self.ticker[tick[0]] = {
                    'last': tick[1],
                    'lowestAsk': tick[2],
                    'highestBid': tick[3],
                    'percentChange': tick[4],
                    'baseVolume': tick[5],
                    'quoteVolume': tick[6],
                    'isFrozen': tick[7],
                    'high24hr': tick[8],
                    'low24hr': tick[9],
                    'id': self.ticker[tick[0]]['id']
                }
        print("Done catching...")

    def start(self):
        """ Start the ticker """
        print("Starting ticker")
        self._appProcess = Process(
            target=self._appRunner.run,
            args=(TickPitcher,)
        )
        self._appProcess.daemon = True
        self._appProcess.start()
        self._running = True
        print('TICKER: tickPitcher process started')
        self._tickThread = Thread(target=self.tickCatcher)
        self._tickThread.deamon = True
        self._tickThread.start()
        print('TICKER: tickCatcher thread started')

    def stop(self):
        """ Stop the ticker """
        print("Stopping ticker")
        self._appProcess.terminate()
        print("Joining Process")
        self._appProcess.join()
        print("Joining thread")
        self._running = False
        self._tickThread.join()
        print("Ticker stopped.")

if __name__ == '__main__':
    import time
    ticker = Ticker()
    ticker.start()
    for i in range(10):
        print(ticker()['BTC_ETH']['last'])
        time.sleep(10)
    ticker.stop()
    print("Done")

**Comment by s4w3d0ff** [comment]
When I tested the dumb ticker and wsMongoTicker.py I found no problems:  


`dumbTicker.py`
```
s4w3d0ff@8core/m/s/E/P/p/e/ticker> python dumbTicker.py 
INFO:__main__:Ticker started
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): poloniex.com
2495.99999998
2495.99999998
INFO:__main__:Ticker updated
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): poloniex.com
2504.64949999
INFO:__main__:Ticker updated
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): poloniex.com
2504.64949999
INFO:__main__:Ticker updated
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): poloniex.com
2503.82762504
INFO:__main__:Ticker updated
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): poloniex.com
INFO:__main__:Ticker updated
^CINFO:__main__:Ticker stopped
```


`wsMongoTicker.py`
```
s4w3d0ff@8core/m/s/E/P/p/e/ticker> python wsMongoTicker.py  
Thread started
Populated markets database with ticker data
Subscribed to ticker
{u'_id': u'USDT_BTC',
 u'baseVolume': u'26753769.05017375',
 u'high24hr': u'2602.93242467',
 u'highestBid': u'2502.00000001',
 u'id': 121.0,
 u'isFrozen': 0,
 u'last': u'2504.64949999',
 u'low24hr': u'2423.00000000',
 u'lowestAsk': u'2504.64949999',
 u'percentChange': u'-0.03108336',
 u'quoteVolume': u'10608.96293618'}
{u'_id': u'USDT_BTC',
 u'baseVolume': u'26777154.49867539',
 u'high24hr': u'2602.93242467',
 u'highestBid': u'2501.99732395',
 u'id': 121.0,
 u'isFrozen': 0,
 u'last': u'2501.99732394',
 u'low24hr': u'2423.00000000',
 u'lowestAsk': u'2504.64949998',
 u'percentChange': u'-0.03210935',
 u'quoteVolume': u'10618.43132969'}
^CTraceback (most recent call last):
  File "wsMongoTicker.py", line 102, in <module>
    sleep(10)
KeyboardInterrupt
s4w3d0ff@8core/m/s/E/P/p/e/ticker>
```


`queuedTicker.py`
```
s4w3d0ff@8core/m/s/E/P/p/e/ticker> python queuedTicker.py
Starting ticker
TICKER: tickPitcher process started
Catching...
TICKER: tickCatcher thread started
0.09932235
2017-07-07T11:18:00-0700 dropping connection to peer tcp4:104.20.13.48:443 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)
0.09932235
^CTraceback (most recent call last):
  File "queuedTicker.py", line 98, in <module>
    time.sleep(10)
KeyboardInterrupt
2017-07-07T11:18:13-0700 Received SIGINT, shutting down.
2017-07-07T11:18:13-0700 Main loop terminated.
```


`mongoTicker.py`
```
s4w3d0ff@8core/m/s/E/P/p/e/ticker> python mongoTicker.py
2017-07-07T11:20:01-0700 dropping connection to peer tcp4:104.20.12.48:443 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)
USDT_BTC: lowestAsk= 2504.64949998
USDT_BTC: lowestAsk= 2504.64949998
^CTraceback (most recent call last):
  File "mongoTicker.py", line 105, in <module>
    sleep(10)
KeyboardInterrupt
2017-07-07T11:20:19-0700 Received SIGINT, shutting down.
2017-07-07T11:20:19-0700 Main loop terminated.
```

Both the `mongoTicker.py` and `queuedTicker.py` use WAMP to connect to the api, but as stated before, it has issues connecting (#115). What happens is that the WAMP websocket never gets connected and throws this error: 
```
2017-07-07T11:20:01-0700 dropping connection to peer tcp4:104.20.12.48:443 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)
```
The ticker (mongoTicker.py and queuedTicker.py) does not know that it is not connected to the websocket but still has its initial ticker data within the mongodb (filled by calling `Poloniex().returnTicker()` before trying to connect the websocket), so the price you see returned is the same, forever, because the websocket isn't sending in new data to update the database with.


If you want realtime ticker updates, IMO stay away from the WAMP api, use `wsMongoTicker.py`, it seems to be the most reliable.

**Comment by tunage** [comment]
dumbTicker was failing to update because of a local issue. That is fixed now.

but wsMongoTicker (and the others) keeps giving me an error 111 'connection refused'.
I turned off firewall and tried a Linode VPS.


connection output:

```
$ python3 examples/ticker/wsMongoTicker.py 
Traceback (most recent call last):
  File "examples/ticker/wsMongoTicker.py", line 99, in <module>
    ticker = wsTicker()
  File "examples/ticker/wsMongoTicker.py", line 22, in __init__
    self.db.drop()
  File "/usr/local/lib/python3.5/dist-packages/pymongo/collection.py", line 962, in drop
    self.__database.drop_collection(self.__name)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 576, in drop_collection
    ReadPreference.PRIMARY) as (sock_info, slave_ok):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", line 859, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", line 823, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/usr/local/lib/python3.5/dist-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```


any thoughts on what might be causing that?
I appear to have all of the preqs installed.

**Comment by s4w3d0ff** [comment]
Looks like pymongo is having trouble connecting to the mongodb server.

Be sure you have 'mongod' (the mongodb server process) running on your machine. 

Interesting that you got the `dumbTicker.py` working (which uses mongodb) but the 'wsMongoTicker.py' isn't connecting.

Seems the origin of the error is line 22 `self.db.drop()` (which is there just in case you have a 'poloniex.ticker' collection in your mongodb that could conflict with updates). Maybe comment out/remove that line and see if it works.

**Comment by tunage** [comment]
That was it!
Thank you!
