### ISSUE TITLE
Met error : HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by archerhu77** [s4w3d0ff/python-poloniex#142]
I do the test according guide, but met following error information:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "poloniex.py", line 58, in returnTicker
    return self.api_query("returnTicker")
  File "poloniex.py", line 36, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/public?command=' + command))
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by s4w3d0ff** [comment]
Seems like you aren't using this wrapper.

```
pip uninstall poloniex
pip install git+https://github.com/s4w3d0ff/python-poloniex.git
```

**Comment by archerhu77** [comment]
@s4w3d0ff , I try to following your instruction but still error.


    [root@localhost ~]# pip uninstall poloniex

    Uninstalling poloniex-0.4.6:
      /usr/lib/python2.7/site-packages/poloniex-0.4.6-py2.7.egg-info
      /usr/lib/python2.7/site-packages/poloniex/__init__.py
      /usr/lib/python2.7/site-packages/poloniex/__init__.pyc
      /usr/lib/python2.7/site-packages/poloniex/coach.py
      /usr/lib/python2.7/site-packages/poloniex/coach.pyc
    Proceed (y/n)? y
      Successfully uninstalled poloniex-0.4.6

    [root@localhost ~]# pip install git+https://github.com/s4w3d0ff/python-poloniex.git
    Collecting git+https://github.com/s4w3d0ff/python-poloniex.git
      Cloning https://github.com/s4w3d0ff/python-poloniex.git to /tmp/pip-njAnXG-build
    Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from poloniex==0.4.6)
    Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->poloniex==0.4.6)
    Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests->poloniex==0.4.6)
    Requirement already satisfied: idna<2.6,>=2.5 in /usr/lib/python2.7/site-packages (from requests->poloniex==0.4.6)
    Requirement already satisfied: urllib3<1.22,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests->poloniex==0.4.6)
    Installing collected packages: poloniex
      Found existing installation: poloniex 0.3.5
        Uninstalling poloniex-0.3.5:
          Successfully uninstalled poloniex-0.3.5
      Running setup.py install for poloniex ... done
    Successfully installed poloniex-0.4.6

    [root@localhost ~]# python
    Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from poloniex import Poloniex
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name Poloniex

**Comment by archerhu77** [comment]
@s4w3d0ff how can I solve this problem?

**Comment by s4w3d0ff** [comment]
It looks to me like your package manager isn't configured correctly. This might be because you are logged in as root.

I usually use `pip install <package> --user` which reduces the amount of conflicts. Sometimes pip recommends using the `sudo -U` flag if you need to install a package as root.

The reason I think this is because:
1.`[root@localhost ~]#` shows that you are logged in as root.
2. your first traceback said the error originated from `File "poloniex.py", line 36, in api_query`. This wrapper does not have an 'api_query' function, nor is there a poloniex.py file. Could you have a `poloniex.py` file in your working project folder?
3. when you did the first uninstall it removed `poloniex-0.4.6` then when you installed it it removed `poloniex-0.3.5` (where did it come from?)

I recommend not being logged in as root and using `pip install <package> --user` to install pip packages.

**Comment by s4w3d0ff** [comment]
Also, in your first traceback, the dir that your system was pulling python packages out of was: `/usr/lib64/python2.7/` then the install said it was uninstalling and installing in `/usr/lib/python2.7/`. This is probably not crorrect.

**Comment by archerhu77** [comment]
@s4w3d0ff  You are quite right! That's a poloniex.py which I copy from poloniex.com(offical API file) in same directory. When I delete this file, import is correct. But seems that return some information in wrong format, like following:

    [root@localhost ~]# python
    Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from poloniex import Poloniex
    >>> polo = Poloniex()
    >>> print(polo.returnTicker()['BTC_ETH'])
    No handlers could be found for logger "poloniex"
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/poloniex/__init__.py", line 276, in returnTicker
        return self.__call__('returnTicker')
      File "/usr/lib/python2.7/site-packages/poloniex/__init__.py", line 143, in retrying
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/poloniex/__init__.py", line 218, in __call__
        return self.handleReturned(ret.text)
      File "/usr/lib/python2.7/site-packages/poloniex/__init__.py", line 251, in handleReturned
        raise PoloniexError('Invalid json response returned')
    poloniex.PoloniexError: Invalid json response returned
    >>>

**Comment by s4w3d0ff** [comment]
Your going to have to contact poloniex support and see if they can sort it out. They might have extra security for whatever region you are located. This has happened in the past and a was resolved through poloniex support.

**Comment by archerhu77** [comment]
I'll try to contact tech support of poloniex, thanks a lot!

**Comment by geekguy** [comment]
Any update on this? Still it's the same error.
