### ISSUE TITLE
Stop Limit 

### ISSUE THREAD

**Issue by angelomelonas** [s4w3d0ff/python-poloniex#143]
Would it be possible to add a stop-limit feature to this API, given Poloniex's current [API Documentation](https://poloniex.com/support/api/)?

**Comment by s4w3d0ff** [comment]
I have been trying to devise a way to go about this 'cleanly'. 

One way is to create an order, save the order number, then keep calling `returnOpenOrders` and `returnTicker` to cross reference and see if the order should be canceled/moved. 

I will try to make a 'clean' solution, but it may take awhile and will be added to the examples directory when complete.

**Comment by AngeloMelonas** [comment]
Thanks for the reply (and the great API by the way!).

I am currently using your API to write a very basic bot. For the bot to work, however, I need the stop-limit/trailing stop-loss functionality. I will see if I can come up with something and, if it works, I'll post the code here. I fear it won't be a 'clean' solution, as the code unfortunately will have to keep monitoring the current price (as you suggested) to know when to place the buy/sell order.

**Comment by s4w3d0ff** [comment]
Here is what I got so far, it should act almost exactly as the stop limit feature on poloniex. You just might need to thread the function so it wont block your program with its while loop.

```python
import time
import logging

logger = logging.getLogger(__name__)

def stopLimit(api, market, amount, stop, limit, interval=2, ticker=False):
    # no order yet
    order = False
    logger.debug('%s stop limit set: [Amount]%.8f [Stop]%.8f [Limit]%.8f',
                 market, amount, stop, limit)
    while not order:
        # get new tick
        if not ticker:
            # use returnTicker
            tick = api.returnTicker()[market]
        else:
            # use external ticker
            tick = ticker(market)
        # sell
        if amount < 0 and stop >= tick['highestbid']:
            # sell amount at limit
            order = api.sell(market, limit, abs(amount))
            continue
        # buy
        if amount > 0 and stop <= tick['lowestAsk']:
            # buy amount at limit
            order = api.buy(market, limit, amount)
            continue
        time.sleep(interval)
    logger.debug('%s stop order triggered!', market)
    return order
```

To use it:
```python
from poloniex import Poloniex
logging.basicConfig(level=logging.DEBUG)
polo = Poloniex(key, secret, jsonNums=float)

# create a buying stoplimit:
buyOrder = stopLimit(api=polo, market='BTC_LTC', amount=100, stop=0.023, limit=0.024)

# pass a negative number to 'amount' to create a sell stop limit
sellOrder = stopLimit(api=polo, market='BTC_LTC', amount=-100, stop=0.024, limit=0.023)
```

I will probably expand on this and give it its own class so it can be canceled/moved

**Comment by EfVonZee** [comment]
Hi s4w3d0ff, 

Thanks so much! I haven't had a chance to look at this again, but I will definitely take a look and test this out after work today.

**Comment by aribo** [comment]
That works pretty well. am I wrong to think that with this we can only pass one stoplimit order at time?

**Comment by maysam19** [comment]
Hello @s4w3d0ff any updates on the stop limit code you wrote above in terms of changing any of it? Or should that still work on poloniex today? Appreciate the help!

Best,

Sam

**Comment by s4w3d0ff** [comment]
@maysam19 There is probably a better way to go about this now that the websocket api has become more mature. Using the websocket to trigger the stop would be way more responsive and easier to work with.

@aribo The example above, yes, you would only be able to run one stoplimit at a time unless you threaded the loop somehow (which can be tricky if you don't want rate limit errors from poloniex). Like I said it is probably easier to just run a websocket that triggers stoplimits now. I will update this example once I add the websocket update to the wrapper (should be soon).

**Comment by maysam19** [comment]
Ok thanks please keep us updated when you make the change @s4w3d0ff ! 

Appreciate the response. So when you way one stoplimit at a time, you mean one for a particular order on a particular crypto pair we are placing right? Other than that, so from what I take from your answer, theoretically what you have created above still should work then for now in the meantime as long as we are only trading one pair at a time?

Thanks again for the response ! :)

Best,

Sam

**Comment by s4w3d0ff** [comment]
The above should work, but if you want to run multiple stoplimits you need to thread the above example. In theory it should be able to handle multiple stops on multiple markets, but since it requires threading the Poloniex object it might not work very well. The Poloniex object's 'coach' has a thread lock but I don't think it will work as expected.

I'll make a much better stoplimit that uses the websocket soon.

**Comment by maysam19** [comment]
Awesome!

Sounds good. Please keep us posted on web socket. Appreciate all the kind assistance and have a great weekend.

Best,

Sam

**Comment by s4w3d0ff** [comment]
Here is something I whipped up and seems to work. It functions near the same as the example above but uses the websocket ticker to check if the stopLimit should be triggered or not (based on highestBid and lowestAsk).  All created `StopLimit`s are held in the `CPolo.stopOrders` dict. The keys in the dict are `market_pair+str(stop)` so if you try to make a stopLimit on the same market using the same stop the old stop will probably be overwritten. Once a stop is triggered it will contain the order it placed under `StopLimit.order` you can get the order by using the `StopLimit.__call__()` method, it will return `False` if the stop has not triggered yet.

```python
# you need v0.5.0 to use the websocket
# pip install --user git+https://github.com/s4w3d0ff/python-poloniex.git@dev
import poloniex

class StopLimit(object):
    def __init__(self, market, amount, stop, limit):
        self.market = str(market)
        self.amount = float(amount)
        self.stop = float(stop)
        self.limit = float(limit)
        self.order = False
        self.logger = poloniex.logging.getLogger('StopLimit')
        self.logger.setLevel(poloniex.logging.DEBUG)

    def check(self, lowAsk, highBid):
        # sell
        if self.amount < 0 and self.stop >= float(highBid):
            # sell amount at limit
            # uncomment sell method below and comment out 'self.order = True' to stop testing
            #self.order = self.sell(self.market, self.limit, abs(self.amount))
            self.order = True
            self.logger.info('%s sell stop order triggered! (%s)', self.market, str(self.stop))
        # buy
        if self.amount > 0 and self.stop <= float(lowAsk):
            # buy amount at limit
            # uncomment buy method below and comment out 'self.order = True' to stop testing
            #self.order = self.buy(self.market, self.limit, self.amount)
            self.order = True
            self.logger.info('%s buy stop order triggered! (%s)', self.market, str(self.stop))

    def __call__(self):
        return self.order


class CPolo(poloniex.PoloniexSocketed):
    def __init__(self, *args, **kwargs):
        super(CPolo, self).__init__(*args, **kwargs)
        self.stopOrders = {}

    def on_ticker(self, msg):
        #[ <id>, null,
        #    [<currency pair id>,
        #    "<last trade price>",
        #    "<lowest ask>",
        #    "<highest bid>",
        #    "<percent change in last 24 hours>",
        #    "<base currency volume in last 24 hours>",
        #    "<quote currency volume in last 24 hours>",
        #    <is frozen>,
        #    "<highest trade price in last 24 hours>",
        #    "<lowest trade price in last 24 hours>" ]]
        self._checkStops(msg[2])

    def _checkStops(self, msg):
        #[<currency pair id>,
        #"<last trade price>",
        #"<lowest ask>",
        #"<highest bid>",
        #"<percent change in last 24 hours>",
        #"<base currency volume in last 24 hours>",
        #"<quote currency volume in last 24 hours>",
        #<is frozen>,
        #"<highest trade price in last 24 hours>",
        #"<lowest trade price in last 24 hours>" ]]
        mktid = str(msg[0])
        mkt = self.channels[mktid]['id']
        la = msg[2]
        hb = msg[3]
        for order in self.stopOrders:
            if str(self.stopOrders[order].market) == str(mkt) and not self.stopOrders[order]():
                self.logger.debug('%s lowAsk=%s highBid=%s', mkt, str(la), str(hb))
                self.stopOrders[order].check(la, hb)

    def addStopLimit(self, market, amount, stop, limit):
        self.logger.debug('%s stop limit set: [Amount]%.8f [Stop]%.8f [Limit]%.8f',
                     market, amount, stop, limit)
        self.stopOrders[market+str(stop)] = StopLimit(market, amount, stop, limit)


if __name__ == '__main__':
    import logging
    logging.basicConfig()
    test = CPolo('key', 'secret')
    test.logger.setLevel(logging.DEBUG)
    tick = test.returnTicker()
    test.addStopLimit(market='BTC_LTC',
                      amount=0.5,
                      stop=float(tick['BTC_LTC']['lowestAsk'])+0.000001,
                      limit=float(0.004)
                      )
    test.addStopLimit(market='BTC_LTC',
                      amount=-0.5,
                      stop=float(tick['BTC_LTC']['highestBid'])-0.000001,
                      limit=float(0.004)
                      )
    test.startws(['ticker'])
    poloniex.sleep(50)

```

```
DEBUG:poloniex:BTC_LTC stop limit set: [Amount]0.50000000 [Stop]0.01185521 [Limit]0.00400000
DEBUG:poloniex:BTC_LTC stop limit set: [Amount]-0.50000000 [Stop]0.01184914 [Limit]0.00400000
INFO:poloniex:Websocket thread started
DEBUG:poloniex:Subscribed to ticker
DEBUG:poloniex:BTC_LTC lowAsk=0.01185421 highBid=0.01185013
DEBUG:poloniex:BTC_LTC lowAsk=0.01185421 highBid=0.01185013
DEBUG:poloniex:BTC_LTC lowAsk=0.01185421 highBid=0.01185015
DEBUG:poloniex:BTC_LTC lowAsk=0.01185421 highBid=0.01185015
DEBUG:poloniex:[1010]
DEBUG:poloniex:[1010]
DEBUG:poloniex:[1010]
DEBUG:poloniex:BTC_LTC lowAsk=0.01185506 highBid=0.01185015
DEBUG:poloniex:BTC_LTC lowAsk=0.01185506 highBid=0.01185015
DEBUG:poloniex:BTC_LTC lowAsk=0.01185565 highBid=0.01185015
DEBUG:poloniex:BTC_LTC lowAsk=0.01185565 highBid=0.01185015
INFO:StopLimit:BTC_LTC buy stop order triggered! (0.01185521)
DEBUG:poloniex:BTC_LTC lowAsk=0.01185565 highBid=0.01185018
DEBUG:poloniex:BTC_LTC lowAsk=0.01185565 highBid=0.01185500
DEBUG:poloniex:BTC_LTC lowAsk=0.01185565 highBid=0.01185501
DEBUG:poloniex:BTC_LTC lowAsk=0.01185565 highBid=0.01185505
DEBUG:poloniex:BTC_LTC lowAsk=0.01185565 highBid=0.01185508
DEBUG:poloniex:BTC_LTC lowAsk=0.01185565 highBid=0.01185509
DEBUG:poloniex:BTC_LTC lowAsk=0.01185565 highBid=0.01185510
DEBUG:poloniex:BTC_LTC lowAsk=0.01185565 highBid=0.01185512
```

**Comment by s4w3d0ff** [comment]
A websocket stop limit example is now here: https://github.com/s4w3d0ff/python-poloniex/blob/master/examples/websocket/stopLimit.py
