### ISSUE TITLE
Question: how can we prevent making order send when poloniex is DDOS ?

### ISSUE THREAD

**Issue by yepla** [s4w3d0ff/python-poloniex#144]
Hello,
First does timeout to None wait an answer for ever ?
Because i have a small problem, my trading bot stop i think when poloniex is DDOS !
In fact i think before poloniex is DDOS i send a buy or sell order.
Then the time that my order will be exectued by poloniex, the exchange is DDOS so i wait the order id who never come and my trading bot is stuck :(
I don't figure out how i can unstuck it.
If someone has an idea it would be very appreciated.
Note: the problem happen very little time but each time it s happen i need to restart manually my bot and sometime i loose money ...
I don't want put a timeout too to make order because in this case sometime order are placed long time after a fixed value of the timeout and it s make bug my trading bot too.
Thanks for your help.

**Comment by yepla** [comment]
I think i have found a solution ...
In fact i take the price with a polo.timeout = x with x in seconds
Then after i put my order with polo.timeout = None to be sure the order will post or not properly ...
I keep you in touch if my bot has not bug for long time.
So see you in a week.

**Comment by s4w3d0ff** [comment]
Sorry for the delay, yes, None will make it wait forever.

The timeout param can also take a tuple `timeout=(3.05, 27)`, see: http://docs.python-requests.org/en/master/user/advanced/#timeouts

This will make the request wait 3.05 sec to **connect** and 27 sec to **read** from poloniex, if the connection is not created, and a timeout is raised, we can assume that the request was never received by poloniex, so the command will not be executed on their end.

If a connection is established then we can assume that poloniex has the api request and is processing. So we want to wait as long as possible for a response (**read**). You might even be able to set the timeout to: `timeout=(3, None)` so you wait forever for a response but only wait 3 sec for the connection. 

Something like this should be the default for the timeout anyway.

**Comment by yepla** [comment]
if i put timeout(3.05, None) and make an order
and the connect is done after 3.05 the order will be set ?

**Comment by s4w3d0ff** [comment]
with timeout=(3.05, None), if the timeout is raised poloniex did not receive the request so the order is not sent. 

The retry method will then capture the raised timeout and try the same request again.

**Comment by yepla** [comment]
ok thanks s4w3d0ff for your answer seems like that i can prevent when poloniex is DDOS
