### ISSUE TITLE
Question: does a fillOrKill order can be put in the order book ?

### ISSUE THREAD

**Issue by yepla** [s4w3d0ff/python-poloniex#145]
Hello,
Does a fillOrKill order can be put in the order book or it must be buy or sell at the market ?
Thanks.

**Comment by s4w3d0ff** [comment]
The only thing poloniex says about the 'fillOrKill' flag is:
>A fill-or-kill order will either fill in its entirety or be completely aborted.  

So when you place an order with 'fillOrKill' it wont (shouldn't) create an order unless it can be completely filled. So if you set an order price that does not appear on the orderbook, the order will be aborted (no order will be placed). This flag makes your order 'taker only' (higher fees, but faster compared to setting an order and waiting).

And  'immediateOrCancel' will partially fill an order and cancel the leftovers:
>An immediate-or-cancel order can be partially or completely filled, but any portion of the order that cannot be filled immediately will be canceled rather than left on the order book.  

The low fee (maker only) flag is 'postOnly':
>A post-only order will only be placed if no portion of it fills immediately; this guarantees you will never pay the taker fee on any part of the order that fills.

**Comment by yepla** [comment]
Thanks
