### ISSUE TITLE
Need help understanding Retry Function

### ISSUE THREAD

**Issue by techietrader** [s4w3d0ff/python-poloniex#149]
Hi,
I want a little help understanding retry function.For some, i know it is self explanatory. 
Does retry function keep retrying a particular line of code for the values given in the variable retryDelays if the script is not getting timely values back for a particular api call?
So suppose there is a connection timed out,  it will retry it 0, 2, 5, 30 seconds before actually raising that error or am i understanding it wrongly?

Regards,

**Comment by s4w3d0ff** [comment]
The retry function/decorator will capture any (and all) exceptions raised by the `requests` module then attempt the same exact api request again (same parameters and command) after waiting a number of seconds (0, 2, 5, 30). Once the 30 sec wait is finished and `requests` is still raising exceptions, the list of captured exceptions are displayed and the wrapper stops trying to make the api call.

The retry function will capture `requests` 'timeouts' as well as a few error messages returned from poloniex (ones that ask to 'try again' and such).

You can access the retry delay pattern by:
```python
import poloniex
poloniex.retryDelays = (0, 0)

polo = poloniex.Poloniex()
```

**Comment by yepla** [comment]
I see 4 values in retryDelays.
So if i don't want wait to retry i must write:
poloniex.retryDelays = (0, 0, 0, 0)
?
Thanks.

**Comment by s4w3d0ff** [comment]
You can:
`poloniex.retryDelays = (0,)` if you want it to retry once, immediately
`poloniex.retryDelays = (1,1,1)` retry 3 times with 1 sec wait between each try
`poloniex.retryDelays = (None,)` This should make it never retry

**Comment by techietrader** [comment]
Thanks for clarification.
You are really very Helpful
Can I use retry function with any api of any broker be it equity or commodity or forex?

**Comment by s4w3d0ff** [comment]
The retry function in this repo is specifically designed for this repo/wrapper. It is designed to retry only when `RequestsExceptions` are raised within the wrapper. The function can be modified to work with other exceptions by changing: https://github.com/s4w3d0ff/python-poloniex/blob/master/poloniex/__init__.py#L151

Changing `RequestsException` to what ever exception you want to capture and retry.

IMO you probably want to use another library that is more generalized, like: https://pypi.python.org/pypi/retrying or https://pypi.python.org/pypi/retry/0.9.0
