### ISSUE TITLE
out of gas

### ISSUE THREAD

**Issue by Pier-Gnome** [s4w3d0ff/python-poloniex#159]
I am working on windows, python 3.6.2 and ran out of gas at:
ModuleNotFoundError: No module named 'certifi'
I have installed requests, urllib3, and chardet and am wondering if it's me after reading the Apr 4 comment
"requests has been adopted into python3 core lib'

**Comment by s4w3d0ff** [comment]
I don't think I understand. Did you try installing certifi manually `pip3 install certifi`?

Perhaps try, `pip3 uninstall poloniex` then `pip3 install git+https://github.com/s4w3d0ff/python-poloniex.git`
