### ISSUE TITLE
error: rate cannot be greater than 5%.

### ISSUE THREAD

**Issue by kotsubu0524** [s4w3d0ff/python-poloniex#160]
Hello all

I'm trying to execute a margin sell order but I can not order by error:
error: rate cannot be greater than 5%.

Below is the code

`polo = poloniex.Poloniex(myAPIKey, mySecret, timeout=10, coach=True)`
`margin_sell_result = polo.marginSell("BTC_ETH",0.07,1)`

Rate is not the price? (0.07)
What I should set to "rate"?

thank you.

**Comment by s4w3d0ff** [comment]
Is that all that poloniex says about the error? It might be the sell price/rate or the lendingRate.

**Comment by MarcDev2** [comment]
there is a missing parameter, lending which must be less than 0.05

**Comment by ilbounce** [comment]
There is a mistake in a default value for lendingRate parameter (default 2). You shall pass 0.02 or smth in [0.02, 0.05].
