### ISSUE TITLE
Withdraw XRP: add destination tag

### ISSUE THREAD

**Issue by datbayev** [s4w3d0ff/python-poloniex#161]
Did anyone have experience withdrawing XRP? You have to put "destination tag" param to make it work.

**Comment by s4w3d0ff** [comment]
I recently added a `paymentId` param to `Poloniex.withdraw`, (it is for XMR, im not sure if other coins require it). Can you post the full error from the traceback?

**Comment by datbayev** [comment]
Hmm, 'paymentId' worked well! 

`polo.withdraw(currency='XRP', amount=some_amount, address=some_address, paymentId=some_payment_id)`
