### ISSUE TITLE
module 'poloniex' has no attribute 'Poloniex'

### ISSUE THREAD

**Issue by smhillin** [s4w3d0ff/python-poloniex#162]
I am running the latest distr. of the wrapper and python3.5 on Mac terminal.

**Comment by s4w3d0ff** [comment]
make sure you dont have another file or folder named 'poloniex' in your project folder, then try:
```
pip3 uninstall poloniex
pip3 install git+https://github.com/s4w3d0ff/python-poloniex.git
```

**Comment by vanxv** [comment]
no working @s4w3d0ff

**Comment by alifie** [comment]
Maybe late to the party but s4w3d0ff's fix worked for me. Thanks!
