### ISSUE TITLE
ModuleNotFoundError: No module named 'poloniex'

### ISSUE THREAD

**Issue by Wee7** [s4w3d0ff/python-poloniex#165]
Hi, I install using terminal with 

> pip3 install https://github.com/s4w3d0ff/python-poloniex/archive/v0.4.6.zip

it shows 

> Collecting https://github.com/s4w3d0ff/python-poloniex/archive/v0.4.6.zip
> Downloading https://github.com/s4w3d0ff/python-poloniex/archive/v0.4.6.zip
> Requirement already satisfied (use --upgrade to upgrade): poloniex==0.4.6 from https://github.com/s4w3d0ff/python-poloniex/archive/v0.4.6.zip in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages

but 

> from poloniex import Poloniex

gives

> ModuleNotFoundError: No module named 'poloniex'

**Comment by Wee7** [comment]
Hi sorry this problem is solved after I restart Spyder. Thank you!

**Comment by Bobpick** [comment]
I too am having this problem - and I don't use Spyder.
Here is the code - I'm just doing minimal just to get something output
`from poloniex import Poloniex
polo=Poloniex()
print(polo('returnTicker')['BTC_ETH'])`

I get this as an error:
`
Traceback (most recent call last):
  File "maint.py", line 1, in <module>
    from poloniex import Poloniex
ImportError: cannot import name Poloniex
`
Any suggestions?

**Comment by s4w3d0ff** [comment]
Be sure you are using this repo and not a registered pypi.

Try:
```
pip uninstall poloniex
pip install git+https://github.com/s4w3d0ff/python-poloniex.git
```
Also make sure you don't have a file or folder named 'poloniex' in your working directory.

**Comment by Bobpick** [comment]
I did. I followed every possible step without any change in outcome.
Are there any boilerplate *.py files that you know of that would help in any way?
