### ISSUE TITLE
_handleReturned doesn't return anything

### ISSUE THREAD

**Issue by daebang** [s4w3d0ff/python-poloniex#166]
_handleReturned has to return output.
I guess it should return output once it handles returned data from poloniex.

    def _handleReturned(self, data):
        """ Handles returned data from poloniex"""
        try:
            if not self.jsonNums:
                out = _loads(data, parse_float=str)
            else:
                out = _loads(data,
                             parse_float=self.jsonNums,
                             parse_int=self.jsonNums)
            return out

**Comment by s4w3d0ff** [comment]
Correct, it expects a json string that is returned from the poloniex api. If for some reason the data returned from poloniex is not a json string it will raise an exception and log the raw data at the debug logging level. You can ignore this method for basic use of this wrapper. This is why I added "_" as a prefix to the method name, you don't really need to be concerned with it unless you want to overwrite it.
