### ISSUE TITLE
How do I use proxy?

### ISSUE THREAD

**Issue by DexHunter** [s4w3d0ff/python-poloniex#167]
Hi! I am in a restricted area where poloniex flagged my ip which means I need to click reCAPTCHA in order to query. I have a VPS as proxy server. I know for `requests` I can add something like
```python
    proxies = {'http': 'socks5://127.0.0.1:1080', #or socks5://<usr>:<pwd>@<addr>:<port>
                   'https': 'socks5://127.0.0.1:1080'}
    requests.get(url, proxies=proxies)
```

I wonder if there is any more efficient way to bypass this inconvenience? Thank you.

**Comment by s4w3d0ff** [comment]
Adding **kwargs to the __call__ method and others then passing **kwargs to the get/post functions should work for a quick fix. Unfortunately I can not create the PR because I am short of time.

**Comment by s4w3d0ff** [comment]
I created the PR, I am unable to test it at the moment, please let me know if this works for you and I will add it to the next release (when I find the time to create one).

**Comment by DexHunter** [comment]
@s4w3d0ff Sorry for the late reply. The [PR](https://github.com/s4w3d0ff/python-poloniex/pull/169/commits/64b43a3f75cecab98f17792e4e507db7b04b2613) works fine
