### ISSUE TITLE
Link for third party Libraries used

### ISSUE THREAD

**Issue by Pankul94** [s4w3d0ff/python-poloniex#170]
Hey, trying to use your API but I am finding it difficut to get a hold on the third party libraries that you have used. I got Request :HTTP for humans but that doesnt do it.

Could you please share a link where I can find these.

Thanks

**Comment by s4w3d0ff** [comment]
The only 3rd party requirement is `requests`

All other modules/libraries used come standard with most versions or python (2.7 or higher). Are you using pip? What errors are you coming across?
