### ISSUE TITLE
How to get all tradable currency pairs?

### ISSUE THREAD

**Issue by BernhardSchlegel** [s4w3d0ff/python-poloniex#173]
Nice work, thank you very much. Based on your experience, what's the best way to get all tradedable currency pairs?

the issue with

     [pair for pair in polo.returnTicker().keys()]

is, that it's lacking information like the minimum order size?

Thanks in advance!

**Comment by s4w3d0ff** [comment]
If I recall, the min order size is by parent coin (BTC, ETH, XMR, and USDT). Each is a different size but I don't think there is an api command that outputs the minimum order size. The minimums are only returned in an error message when you try to place an order that is below the minimum.
