### ISSUE TITLE
Porting for micropython

### ISSUE THREAD

**Issue by BoKKeR** [s4w3d0ff/python-poloniex#174]
Hey, how hard would it be to port this wrapper for micropython? I am looking that requests are missing from micropython and are replaced by ureqeusts and probably many more modules need special care.

**Comment by s4w3d0ff** [comment]
I'm not familiar with micropython, but from what I read, you might be able to just add 'u' to the front of some of the imports and it should work (if all the functions used in this wrapper is ported in the 'u' versions). When I find some time I will see how far I can port it and save it in a new branch.

**Comment by BoKKeR** [comment]
I looked some more into it and tried to port some parts but the big issue is that the ram AND memory on these development boards are quite small. It cant load the JSON string from [](https://poloniex.com/public?command=returnTicker) to begin with. To port this properly the code would have to be cut down and simplified. I will probably just stick with a different API like coinmarketcap

**Comment by s4w3d0ff** [comment]
I found these today looking for a way to buffer/stream the incoming data:
https://stackoverflow.com/questions/16694907/how-to-download-large-file-in-python-with-requests-py
https://stackoverflow.com/questions/2400643/is-there-a-memory-efficient-and-fast-way-to-load-big-json-files-in-python

Unfortunately this would require an almost full rewrite of this repo.
