### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by dragosgr2** [s4w3d0ff/python-poloniex#181]
Hi,

Since last week I experienced slow or down APIs with the error Connection Timeout.
Do you see the same thing? Is this a Poloniex issue or mine?

I have a trading bot and it stops because of this issue: trying to retrieve data from Poloniex and get back Connection Timeout error: urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

Do you have an idea how I would pass by this error and let the code run further?

Thanks

**Comment by gerybubus** [comment]
Hi,
If you got this error message, then you can try to catch it with try: ... except:... block and handle the error in the exception block.
But I am also interested in this question.... I'm loading the current order book into my database, just calling the  returnOrderBook() function, but in case of any network issue, then my script is just waiting for response, it never get it... So without any error message just waiting for the response... Even if the network connection is back, just waiting...
How could I handle this network connectivity issue and raise an exception like after 30 sec resend the request?
Thanks,
Greg
