### ISSUE TITLE
sudo pip is a broken practice and should be discouraged

### ISSUE THREAD

**Issue by miohtama** [s4w3d0ff/python-poloniex#19]
I noticed that README recommends `sudo pip` as installation method.

This practice is discouraged by Python community, as it conflicts with operating system package management and might lead to broken Python installations. I recommend guiding using `pip --user` or `virtualenv` instead.

Official Python package installation guide: https://packaging.python.org/en/latest/installing/

Discussion: http://stackoverflow.com/a/33004920/315168

**Comment by s4w3d0ff** [comment]
Thanks for the heads up! `pip --user` or venv is something I have a hard time remembering to do and  my default to 'Operation not permitted' or 'Access denied' is to sudo :P. 
I'll update the READMEs soon.

**Comment by s4w3d0ff** [comment]
dfcdcae
