### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ruttydm** [s4w3d0ff/python-poloniex#20]
It woupd be usefull to add a list of the required dependencies. Or just add requirements.txt.

**Comment by s4w3d0ff** [comment]
This is a very simple module.

The only system requirements is a version of [python](https://www.python.org/downloads/) (2.7 or higher) and [pip](https://pip.pypa.io/en/stable/installing/)

The only python module/package used that is **not** in the python standard libary is the [requests](https://pypi.python.org/pypi/requests) module/package.

Either way, [the setup.py has a param](https://github.com/s4w3d0ff/python-poloniex/blob/master/setup.py#L9) that defines what dependacies to install (in this case just requests) if it is not already installed.

I could make a quick requirements.txt (1 line: `requests`) but after [reading through the docs](https://pip.pypa.io/en/stable/user_guide/#requirements-files) I can't see a need for it.

For extended reading on requirements.txt files: https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by ruttydm** [comment]
I always need to install coach, twisted and autobahn and other modules. I cannot install coach for some reason.

**Comment by s4w3d0ff** [comment]
Ah I see, you must be using python 3, the latest python-poloniex release has the coach moved to its own file and I goofed and [imported the coach incorrectly](https://github.com/s4w3d0ff/python-poloniex/commit/b04d3667bb90d2fed19c4bafb552bdd96b8cb75a#diff-eeaeffee5a0554a0261f80f7b06417c3R34) into the poloniex module. It works on python 2 but not python 3 (another reason why I should probably write unit tests).
>    from coach import *
>ImportError: No module named 'coach'

uninstalling the module and installing the older release should fix it for now. I will fix this asap
```
pip3 uninstall poloniex
pip3 install https://github.com/s4w3d0ff/python-poloniex/archive/v0.0.1.tar.gz
```

Also: ```autobahn[twisted]``` **is not** required for _installing_ the poloniex module. It is only required when connecting to the WAMP push api (which the poloniex module does not wrap at the moment). The polocalbox.py and ticker examples require ```autobahn[twisted]``` because those scripts connect to the push api (the ticker example uses both autobahn and the poloniex module).

**Comment by ruttydm** [comment]
I can' t still run the examples, i need to have markupbase and openssl but i can't do pip3 install.

**Comment by s4w3d0ff** [comment]
Can you post some tracebacks/logs, and the sequence of events leading to the error(s)?
What do you mean you 'can't do pip3 install'?

Check out Issue https://github.com/s4w3d0ff/python-poloniex/issues/9 it might help with push api examples.

**Comment by ruttydm** [comment]
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-38-gene
ric x86_64)                                           
                                                      
 * Documentation:  https://help.ubuntu.com            
 * Management:     https://landscape.canonical.com    
 * Support:        https://ubuntu.com/advantage       
                                                      
  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud     
                                                      
7 packages can be updated.                            
0 updates are security updates.                       
                                                      
                                                      
Last login: Thu Sep 22 12:15:00 2016 from 178.50.83.14
root@vps319088:~# pip3 uninstall poloniex             
                                                      
Uninstalling poloniex-0.1.1:                          
  /usr/local/lib/python3.5/dist-packages/poloniex-0.1.
1.egg-info                                            
  /usr/local/lib/python3.5/dist-packages/poloniex/__in
it__.py                                               
  /usr/local/lib/python3.5/dist-packages/poloniex/__py
cache__/__init__.cpython-35.pyc                       
  /usr/local/lib/python3.5/dist-packages/poloniex/__py
cache__/coach.cpython-35.pyc                          
  /usr/local/lib/python3.5/dist-packages/poloniex/coac
h.py                                                  
Proceed (y/n)? Your response ('') was not one of the e
xpected responses: y, n                               
Proceed (y/n)? y                                      
  Successfully uninstalled poloniex-0.1.1             
root@vps319088:~# pip3 install https://github.com/s4w3
d0ff/python-poloniex/archive/v0.0.1.tar.gz            
Collecting https://github.com/s4w3d0ff/python-poloniex
/archive/v0.0.1.tar.gz                                
  Downloading https://github.com/s4w3d0ff/python-polon
iex/archive/v0.0.1.tar.gz                             
     \ 20kB 254kB/s                                   
Requirement already satisfied (use --upgrade to upgrad
e): requests in /usr/lib/python3/dist-packages (from p
oloniex==0.1)                                         
Installing collected packages: poloniex               
  Running setup.py install for poloniex ... done      
Successfully installed poloniex-0.1                   
root@vps319088:~# ls                                  
root@vps319088:~# cd /                                
root@vps319088:/# cd home/ruttydm                     
root@vps319088:/home/ruttydm# ls                      
python                                                
root@vps319088:/home/ruttydm# cd python               
root@vps319088:/home/ruttydm/python# ls               
python-poloniex                                       
root@vps319088:/home/ruttydm/python# cd python-polonie
x                                                     
root@vps319088:/home/ruttydm/python/python-poloniex# l
s                                                     
examples  LICENSE  poloniex  README.md  setup.py      
root@vps319088:/home/ruttydm/python/python-poloniex# c
d examples                                            
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples# ls                                            
loanbot  localticker  polocalbox.py  README.md        
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples# python3 polocalbox.py                         
Traceback (most recent call last):                    
  File "polocalbox.py", line 4, in <module>           
    from HTMLParser import HTMLParser                 
  File "/usr/local/lib/python3.5/dist-packages/HTMLPar
ser.py", line 11, in <module>                         
    import markupbase                                 
ImportError: No module named 'markupbase'             
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples# pip3 install markupbase                       
Collecting markupbase                                 
  Could not find a version that satisfies the requirem
ent markupbase (from versions: )                      
No matching distribution found for markupbase         
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples# ls                                            
loanbot  localticker  polocalbox.py  README.md        
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples# cd localticker                                
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# ls                                
tickcatcher.py  ticker.py                             
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# python3 ticker.py                 
{'last': '0.02143999', 'isFrozen': '0', 'baseVolume': 
'23209.03961373', 'quoteVolume': '1058684.            
01266058', 'id': 148, 'low24hr': '0.02071200', 'highes
tBid': '0.02143581', 'high24hr': '0.023169            
71', 'percentChange': '-0.06125530', 'lowestAsk': '0.0
2143999'}                                             
TICKER: tickcatcher subprocess started                
TICKER: tickCatcher thread started                    
Traceback (most recent call last):                    
  File "tickcatcher.py", line 1, in <module>          
    from twisted.internet.defer import inlineCallbacks
ImportError: No module named twisted.internet.defer   
^Z                                                    
[1]+  Stopped                 python3 ticker.py       
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# pip3 install twisted              
Requirement already satisfied (use --upgrade to upgrad
e): twisted in /usr/local/lib/python3.5/di            
st-packages                                           
Requirement already satisfied (use --upgrade to upgrad
e): zope.interface>=4.0.2 in /usr/local/li            
b/python3.5/dist-packages (from twisted)              
Requirement already satisfied (use --upgrade to upgrad
e): setuptools in /usr/lib/python3/dist-pa            
ckages (from zope.interface>=4.0.2->twisted)          
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# ls                                
tickcatcher.py  ticker.py                             
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# python3 tickcatcher.py            
2016-09-22T17:52:24+0200 Traceback (most recent call l
ast):                                                 
2016-09-22T17:52:24+0200   File "tickcatcher.py", line
 15, in <module>                                      
2016-09-22T17:52:24+0200     subscriber.run(Subscribe2
Ticker)                                               
2016-09-22T17:52:24+0200   File "/usr/local/lib/python
3.5/dist-packages/autobahn/twisted/wamp.py            
", line 239, in run                                   
2016-09-22T17:52:24+0200     from twisted.internet.ssl
 import optionsForClientTLS                           
2016-09-22T17:52:24+0200   File "/usr/local/lib/python
3.5/dist-packages/twisted/internet/ssl.py"            
, line 59, in <module>                                
2016-09-22T17:52:24+0200     from OpenSSL import SSL  
2016-09-22T17:52:24+0200 ImportError: No module named 
'OpenSSL'                                             
root@vps319088:/home/ruttydm/python/python-poloniex/ex
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# ls                                
tickcatcher.py  ticker.py                             
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# python3 ticker.py                 
{'high24hr': '0.02316971', 'id': 148, 'baseVolume': '2
3592.65603314', 'highestBid': '0.02173494', 'quoteVolu
me': '1076873.80226915', 'lowestAsk': '0.02173694', 'l
ast': '0.02173494', 'isFrozen': '0', 'percentChange': 
'-0.04863258', 'low24hr': '0.02071200'}               
TICKER: tickcatcher subprocess started                
TICKER: tickCatcher thread started                    
Traceback (most recent call last):                    
  File "tickcatcher.py", line 1, in <module>          
    from twisted.internet.defer import inlineCallbacks
ImportError: No module named twisted.internet.defer   
pip3 install twisted.intTICKER: Ticker subprocess stop
ped                                                   
TICKER: Ticker thread joined                          
{'high24hr': '0.02316971', 'id': 148, 'baseVolume': '2
3592.65603314', 'highestBid': '0.02173494', 'quoteVolu
me': '1076873.80226915', 'lowestAsk': '0.02173694', 'l
ast': '0.02173494', 'isFrozen': '0', 'percentChange': 
'-0.04863258', 'low24hr': '0.02071200'}               
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# pip3 install twisted.internet.defe
r                                                     
Collecting twisted.internet.defer                     
  Could not find a version that satisfies the requirem
ent twisted.internet.defer (from versions: )          
No matching distribution found for twisted.internet.de
fer                                                   
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# ls                                
tickcatcher.py  ticker.py                             
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# python3 tickcatcher.py            
2016-09-22T18:18:36+0200 Traceback (most recent call l
ast):                                                 
2016-09-22T18:18:36+0200   File "tickcatcher.py", line
 15, in <module>                                      
2016-09-22T18:18:36+0200     subscriber.run(Subscribe2
Ticker)                                               
2016-09-22T18:18:36+0200   File "/usr/local/lib/python
3.5/dist-packages/autobahn/twisted/wamp.py", line 239,
 in run                                               
2016-09-22T18:18:36+0200     from twisted.internet.ssl
 import optionsForClientTLS                           
2016-09-22T18:18:36+0200   File "/usr/local/lib/python
3.5/dist-packages/twisted/internet/ssl.py", line 59, i
n <module>                                            
2016-09-22T18:18:36+0200     from OpenSSL import SSL  
2016-09-22T18:18:36+0200 ImportError: No module named 
'OpenSSL'                                             
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# pip3 install openssl              
Collecting openssl                                    
  Could not find a version that satisfies the requirem
ent openssl (from versions: )                         
No matching distribution found for openssl            
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# ls                                
tickcatcher.py  ticker.py                             
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples/localticker# cd ..                             
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples# ls                                            
loanbot  localticker  polocalbox.py  README.md        
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples# python3 polocalbox.py                         
Traceback (most recent call last):                    
  File "polocalbox.py", line 4, in <module>           
    from HTMLParser import HTMLParser                 
  File "/usr/local/lib/python3.5/dist-packages/HTMLPar
ser.py", line 11, in <module>                         
    import markupbase                                 
ImportError: No module named 'markupbase'             
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples# pip3 install markupbase                       
Collecting markupbase                                 
  Could not find a version that satisfies the requirem
ent markupbase (from versions: )                      
No matching distribution found for markupbase         
root@vps319088:/home/ruttydm/python/python-poloniex/ex
amples#

**Comment by s4w3d0ff** [comment]
This works for me on Ubuntu 16
```
sudo apt-get install build-essential libssl-dev python3-pip libffi-dev git
sudo apt update; sudo apt upgrade
sudo apt install python-dev
pip3 install service_identity
pip3 install autobahn[twisted]
pip3 install git+https://github.com/s4w3d0ff/python-poloniex.git
git clone https://github.com/s4w3d0ff/python-poloniex.git
cd python-poloniex/examples
python3 polocalbox.py
```

**Comment by ruttydm** [comment]
It works now. But it doesn't work with pm2 process manager.

**Comment by s4w3d0ff** [comment]
Not sure what pm2 is... if it is this: https://github.com/Unitech/pm2 then it wont work because this is a python program and pm2 is for node.js programs.

**Comment by s4w3d0ff** [comment]
You could probably make it work if you wrote a node.js script that just ran the python script, then run the node.js script from pm2

**Comment by ruttydm** [comment]
pm2 can run python, it is not only for js

**Comment by s4w3d0ff** [comment]
I don't see anything in the docs that says it can, doing a brief google and not much shows up except that some claim that it works and others claiming it doesn't. Anyway... I know nothing of node.js so I can't help you there.

Might want to open an issue with pm2, seems pm2 can't find the correct path to the pip installed python libraries (perhaps because of sudo?).

**Comment by ruttydm** [comment]
> [edit] I also get this error with python3 ticker.py

I tried this and it doesn't work too. I got the same error with and without sudo.

**Comment by s4w3d0ff** [comment]
The ticker (when working) is super buggy and not really recommended for use.

Is the error "the JSON object must be str, not 'bytes'"? 

This is a bytes to unicode error that happens a lot when running python2 code under python3. The string just needs to be converted. I'll see if I can fix it later. It does work in python 2.

**Comment by s4w3d0ff** [comment]
Updated the ticker.py example #21. Should be pretty solid now, except for this: #13 but that is (once again) beyond my skill level.

Thanks for bringing these bugs to my attention!
