### ISSUE TITLE
sos GET OPEN ORDERS

### ISSUE THREAD

**Issue by emanuelecesari** [s4w3d0ff/python-poloniex#23]
Hello i am a young developer this is my first time with the api of poloniex, I am developing a python bot for Poloniex , but is all the day that i try to make a request to get the open order but it fails!!
My code is very similar to your but I dont know, why it dosent works the request status is 200 but this is the reply:
{'error': 'Invalid command.'}

this is my code:
`# Returns open orders for a given market

    def getOpenOrders(self,url,comand, market):
     
        nonce = int(time.time())
        urlrequest = url  + '?apikey=' + self.apiKey +'&command='+comand + '&nonce=' +str(nonce) + '&market=' + str(market)
        print(urlrequest)
        param =  'command='+comand + '&nonce=' +str(nonce) + "&market=" +str(market)
        signature =  hmac.new(self.Secret.encode(),param.encode(), hashlib.sha512).hexdigest()
        headers = {
                'Sign':signature,
                'Key': self.apiKey
            }

        self.r = requests.post(urlrequest,headers= headers,)
        print(self.r)
        print(self.r.json())

        

could you help me to fix??

i hope to receive your answear and sorry again`

**Comment by s4w3d0ff** [comment]
If you use this repo:

To get the **public order book** for a market you need to send poloniex:

```python
import poloniex
polo = poloniex.Poloniex()
orders = polo.marketOrders(pair='BTC_CGA', depth=10)
print(orders)
#or
orders = polo.api('returnOrderBook', { 'currencyPair': 'BTC_CGA', 'depth': '10' } )
print(orders)
```

To get your **personal order book**:
```python
import poloniex
polo = poloniex.Poloniex('YOUR-TRADE-API-KEY-HERE', 'YourApiSecretKeyGoesHere')
orders = polo.myOrders(pair='all')
print(orders)
#or
orders = polo.api('returnOpenOrders', {'currencyPair': 'all'})
print(orders)
```

**Comment by s4w3d0ff** [comment]
Everything you are trying to write code for has already been done for you. You just need to install and use an api wrapper (like this repo!).

**Comment by emanuelecesari** [comment]
ok i will do it is better dont reinvent the wheeil

**Comment by s4w3d0ff** [comment]
[This function](https://github.com/s4w3d0ff/python-poloniex/blob/master/poloniex/__init__.py#L119) is probably what you are looking for. It identifies the command as public or private, then encodes the command as a url and posts the request. If the command is "*private*" then the function will sign the headers and send the request with the encoded url and signed headers. It is all wrapped in a class called `Poloniex` that holds the api key and secret. It also keeps nonces in order and has a call limiter called `coach`.

**Comment by emanuelecesari** [comment]
now everthing works good 
thank you so much !!

i really suggest to use this library
