### ISSUE TITLE
returnOrderTrades not working

### ISSUE THREAD

**Issue by risingsun007** [s4w3d0ff/python-poloniex#37]
When I try to implement the returnOrderTrades function I receive the response "Order not found, or you are not the person who placed it.'   However, with the exact same orderNumber I tried with returnOrderTrades, I can cancel the order with no error.

**Comment by s4w3d0ff** [comment]
That seems like an issue on Polos end (or your order has no trades?)

**Comment by s4w3d0ff** [comment]
Seems like that is the error you get if no trades have occurred for that order:
https://poloniex.com/support/api/
> ...If no trades for the order have occurred or you specify an order that does not belong to you, you will receive an error...
