### ISSUE TITLE
How does one use returnDepositsWithdrawals() ?

### ISSUE THREAD

**Issue by outragedhuman** [s4w3d0ff/python-poloniex#40]
Using the 2.x version, when I do the following:

```
import config
import poloniex

polo = poloniex.Poloniex(config.polo_api_key, config.polo_api_secret)

resp = polo.returnDepositsWithdrawals()
print resp
```

I get:

`{u'error': u'Required parameter missing.'}`

I believe it wants the "start" and "end" parameters mentioned [here](https://poloniex.com/support/api/):

"Returns your deposit and withdrawal history within a range, specified by the "start" and "end" POST parameters, both of which should be given as UNIX timestamps."

Attempting to call it with parameters it doesn't like that:

```
resp = polo.returnDepositsWithdrawals(5,10)

TypeError: returnDepositsWithdrawals() takes exactly 1 argument (3 given)
```

Is this currently not supported?

**Comment by kdb424** [comment]
You can't add any args. It only accepts self. You'll have to get a full return and then process the output from there.

**Comment by outragedhuman** [comment]
@kdb424 Check the first part of my post again, I tried it with empty args and it errored.

**Comment by kdb424** [comment]
Just tried it again. You are indeed correct. I'll keep digging.

**Comment by outragedhuman** [comment]
I'd even be fine with leaving it self-only and you can just use:

```
start = 0
end = current.epoch.time
```

Parsing the response wouldn't be the end of the world if it's easier to implement that for now.

**Comment by kdb424** [comment]
https://github.com/s4w3d0ff/python-poloniex/pull/41
Pull request incoming with tested fix.

**Comment by outragedhuman** [comment]
Thank you very much! 👍
