### ISSUE TITLE
'Poloniex' object has no attribute 'sell'

### ISSUE THREAD

**Issue by cardboard11** [s4w3d0ff/python-poloniex#43]
Hi there! First of all, thank you very much for your work.
I'm pretty new in coding, had some experience in bots in python but this one is something new.
I have a problem with "sell" method. When I try to use for polo. sell I get message:
'Poloniex' object has no attribute 'sell'
Also in __init__.py file, there is "def buy" but there is no "def sell" ?
Thank you for any help.

**Comment by kdb424** [comment]
That was probably my last commit that I asked to pull. I was messing around in that area of the file and think I made a wrong merger. Give me a second to take care of it.

**Comment by kdb424** [comment]
Sorted. Works on my fork now. Pull request submitted for review. Sorry for the trouble.

**Comment by cardboard11** [comment]
Oh, no need to sorry:)
OK, probably I am missing something but I still can't see "def sell". Also I copied the whole __init__ file from here:
https://github.com/s4w3d0ff/python-poloniex/pull/44/commits/8cc6264340a2f4df61f74ef0f81b41383270de61
and get the same error. When you compare the changes, seems that the only "def buy" was added? I wish I had more experience in this stuff:)

**Comment by kdb424** [comment]
I have no idea how I did this, but I grabbed buy AGAIN and not sell. New fix incoming. Sorry for the troubles. Really long day.

**Comment by cardboard11** [comment]
No problem:)
I tried to fix the problem myself by addig to _init_:
`    def sell(self, pair, rate, amount):
        req = {
            'currencyPair': str(pair).upper(),
            'rate': str(rate),
            'amount': str(amount)
        }
        return self.__call__('sell', req)`

But get the same error - 'Poloniex' object has no attribute 'sell'
Wonder why as this should fix the problem in my understanding.
Have a great week:)

**Comment by kdb424** [comment]
https://github.com/s4w3d0ff/python-poloniex/pull/45

**Comment by cardboard11** [comment]
OK, for future reference:
Even though I had poloniex installed in /home/>user</.local/lib/python3.5/site-packages
there was a second copy, which python3 was using, installed in:
/usr/local/lib/python3.5/dist-packages
I had to update the disc-package and everything works:) Long day indeed. Cheers!

**Comment by kdb424** [comment]
Is this still an issue or just not closed yet? Just want to make sure things are fixed.

**Comment by cardboard11** [comment]
Yes, it is fixed. Thank you.

**Comment by s4w3d0ff** [comment]
While minor work is still being done in this area of the code I don't think any this issue is relevant anymore and has been fixed.
