### ISSUE TITLE
sell orders not going through

### ISSUE THREAD

**Issue by wreckednerd** [s4w3d0ff/python-poloniex#46]
I'm trying to test the sell function. when i run it it runs no problem, but no sell order opens on poloniex. 
Im calling it by

polo.sell('BTC_VTC',0.00003879,vtcBal)
 where vtcBal is set by 
balance = polo.returnBalances()
vtcBal = balance['VTC']

am i formatting this wrong or is there something missing from my arguments?

**Comment by kdb424** [comment]
https://github.com/s4w3d0ff/python-poloniex/issues/43
Does that sort it by using my fork?

**Comment by wreckednerd** [comment]
a1 dude, new to git and python, but i just copied your fork over the old _init_ file, worked great. thanks
