### ISSUE TITLE
Coach.py must be str, not bytes

### ISSUE THREAD

**Issue by MichaelsTechCenter** [s4w3d0ff/python-poloniex#48]
logging.info(
                "Now: %d  Oldest Call: %d  Diff: %f sec" %
                (now, self._timeBook[-1], now - self._timeBook[-1])
                )

Is the error origin. Running python 3.6.0.

**Comment by kdb424** [comment]
Can you please let us know what steps you took to get this error? I am not having any issues when importing with coach and calling any action. I'm willing to sort it if I can reproduce the error.

**Comment by MichaelsTechCenter** [comment]
Thank you for responding kdb424. First, it is important to share that this is my first real program that I'm developing. I don't understand half of what is going on. I issue arises when I use coach=Enable in my program. I haven't altered any coach.py settings. I just turned it on so it will limit my requests.

**Comment by kdb424** [comment]
I have python3.6, and have enabled coach, and can make calls with no issues. Can I get a sample bit of code that is causing the issue so I can test it? Please make sure you strip your API key and secret if you are using them.

**Comment by s4w3d0ff** [comment]
This seems like the error you would get if one were to try and run python2 only code in python3, which means it would be some mistake on my part (if the error is indeed originating from the line of code quoted). 

As kdb4244 said, if you can reproduce the error and "copy paste" the code you are trying to run along with the full error, we can take a deeper look into the issue.

**Comment by s4w3d0ff** [comment]
Now that the coach is in the process of changing (#66), I am going to close this issue. 

If the bug is still there after the update, we will take take of it then.
