### ISSUE TITLE
Buy method not actually buying

### ISSUE THREAD

**Issue by wreckednerd** [s4w3d0ff/python-poloniex#51]
polo.buy('BTC_VRC', float(ticker['BTC_VRC']['lowestAsk']),  (.1 * btcBal))

running that will not throw any errors, but wont actually buy anything. everything else seems to be working, and i have tried other coins in the arguments.

**Comment by s4w3d0ff** [comment]
what branch/release are you using?

**Comment by wreckednerd** [comment]
most recent master

**Comment by s4w3d0ff** [comment]
When I try something similar:
```python
polo = poloniex.Poloniex(Key = KEY, Secret = SECRET, loglevel=logging.DEBUG)

print(
    polo.buy(
        pair='BTC_BTM',
        rate=polo.returnTicker()['BTC_BTM']['lowestAsk'],
        amount=polo.returnBalances()['BTC'])
    )
```
The data/url seems legit:
>https://poloniex.com/tradingApi?nonce=1486987377881&amount=0.03925396&rate=0.00012015&command=buy&currencyPair=BTC_BTM

but I get this error (only with buy orders):
```
[04:02:59] Starting new HTTPS connection (1): poloniex.com
[04:02:59] "POST /tradingApi HTTP/1.1" 200 None
[04:02:59] {"error":"Total must be at least 0.0001."}
{u'error': u'Total must be at least 0.0001.'}
```

The order I am trying to place is well above 0.0001, unless I am missing something obvious...

**Comment by wreckednerd** [comment]
is the total amount of btc bought greater than 0.0001? as in btm lowest ask * btc balance > .0001?

**Comment by wreckednerd** [comment]
even hard coding values ie 
(polo.buy('BTC_MAID', 0.00018864, .001))
returns the error {'error': 'Total must be at least 0.0001.'} still. did poloniex change the way they take arguments?

**Comment by kdb424** [comment]
Last I tried this on my fork which is almost completely up to date with the head of this repo it worked. Will test tonight with either a patch or a working solution.

**Comment by wreckednerd** [comment]
ill try it with your fork and see if that works will edit comment with results

**Comment by wreckednerd** [comment]
think i mightve figured it out. amount is now the amount of the coin you want to buy rather than the total amount of btc youd like to spend. 

so  (polo.buy('BTC_MAID', 0.00018864, 1) buys 1 MAID rather than 1btc's worth of Maid

**Comment by s4w3d0ff** [comment]
That would make sense. I cant remember if it was this way before... or if Polo changed it recently. Ether way, it isnt specified in their docs.

**Comment by wreckednerd** [comment]
i have it working just had to change up my logic a bit. I think before it definitely was the final btc being used.
