### ISSUE TITLE
Trollbox does not return continuous messages 

### ISSUE THREAD

**Issue by saitam1** [s4w3d0ff/python-poloniex#52]
Hi

I don't know why, but your example code for the Trollbox doesn't work. The programm runs, but returns nothing.

I use a very similar code which works, but unfortunately Poloniex doesn't return everytime continuous trollbox messages. Is there a reason for this behaviour? Sometimes I get continuous message numbers, but sometimes there are like 10 or 20 or 30 messages missing before the next message with the next number appears. 

This is my code, its almost the same as yours:

```
from autobahn.asyncio.wamp import ApplicationSession
from autobahn.asyncio.wamp import ApplicationRunner
from asyncio import coroutine

class PoloniexComponent(ApplicationSession):
    def onConnect(self):
        self.join(self.config.realm)

    @coroutine
    def onJoin(self, details):
        def onTrollbox(*args):

            print("type: ", args[0])
            print("message_number: ", args[1])
            print("user_name: ", args[2])
            print("message: ", args[3])
            print("reputation: ", args[4])

        try:
            yield from self.subscribe(onTrollbox, 'trollbox')
        except Exception as e:
            print("Could not subscribe to topic:", e)

runner = ApplicationRunner("wss://api.poloniex.com", "realm1")
runner.run(PoloniexComponent)
```
Many thanks for ever help on this topic.

**Comment by s4w3d0ff** [comment]
Seems similar to issue #13, TBH I'm not too familiar with WAMP or Push APIs and the push examples were never tested for an extended amount of time (at least not by me).

I just tested polocalbox.py and it is displaying the messages as intended (on ubuntu 16, python2.7.12). 

Your code seems fine to me (except for banhammer messages, you will get an 'IndexError'). 

You can try to capture a disconnect event and try to reconnect, sorta like: https://github.com/s4w3d0ff/python-poloniex/blob/v0.2.2/examples/ticker.py#L22 but using asyncio... or you can try using https://github.com/isra17/autobahn-autoreconnect

It could just be (and probably is) Poloniex.... but then all you can do is attempt to write your code around their bugs...

**Comment by skyl** [comment]
For anyone else coming to this issue, the key difference in the code (for me) is that:

```
from autobahn.asyncio.wamp import ApplicationSession
from autobahn.asyncio.wamp import ApplicationRunner
```

works and

```
from autobahn.twisted.wamp import ApplicationRunner
from autobahn.twisted.wamp import ApplicationSession
```

does not. It took me some time to figure that out - maybe this will save someone else some time.

**Comment by s4w3d0ff** [comment]
If you are using python3, `autobahn[asyncio]` is probably easier to set up (and possibly less buggy). I have `autobahn[twisted]` working on both python 3 and 3, but `asycnio` seems to work better overall.
