### ISSUE TITLE
Receive error "Invalid Command" for PRIVATE_COMMANDS

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [s4w3d0ff/python-poloniex#57]
As the title states, I have been attempting to use this wrapper, and am able to properly make public calls without issues. However, when I attempt to make any private calls (eg. buy, getBalances, etc) using my api keys I receive an error stating invalid command. I have made my code spit out the key and secret being input into the wrapper and all seems well there. However I am still unable to make privileged calls. 

Is this an issue with poloniex? Could they be updating their API calls? Or is it more likely my code is fudged up?

my code:
http://pastebin.com/WSj30Se2 <- edited to a more trustworthy website.

I have attempted your instructions, however no matter how i work it it always seems to give an error stating {u'error': u'Invalid command.'}
However I am 100% sure the issue is my own, I must be missing something or mistyping something. Thank you for responding, I will close as soon as I figure out where my issue is :)
`    apikey = (defined earlier in program)`
`    apisecret = (same as above)`
`    polo = poloniex.Poloniex(apikey, apisecret, extend=True)`
`    print polo.returnBalances()` or `print polo.myBalances()`
returns the error stated above within IDLE or within a program. Could my issue be that im using python2 and not python3?

**Comment by s4w3d0ff** [comment]
The link you posted is showing as untrusted in Firefox...

This worked for me:
```python
import poloniex
key = '123MY-345API-KEY-ISHERE'
secret = 'mySuP3Rs3creTHashedK3yFr0mP0lo'
poloniex.Poloniex(key, secret).returnBalances()
```
If you are trying to use `poloniex.Poloniex().myBalances()` (there is no `getBalances`) you need to pass `extend=True` when creating the Poloniex instance:
```python
import poloniex
key = '123MY-345API-KEY-ISHERE'
secret = 'mySuP3Rs3creTHashedK3yFr0mP0lo'
polo = poloniex.Poloniex(key, secret, extend=True)
polo.getBalances()
```
This feature __will be (_is_) [removed from v0.3](https://github.com/s4w3d0ff/python-poloniex/commit/ee82da4c70ab1c9eb374ed67c83a212a83bce0b8) (not yet released)__ and the _only method/command that won't exactly match the polo api_ is the public trade history (`Poloniex.marketTradeHist()`).

So I suggest just using `returnBalances`

**Comment by s4w3d0ff** [comment]
`{u'error': u'Invalid command.'}` is a response from poloniex, so the wrapper could be the issue, possibly sending a bad request. The wrapper is supposed to prevent bad requests like this.

If you use the 'extra-debug' branch and try `Poloniex(loglevel=logging.DEBUG)` you should be able to inspect the url sent to poloniex.

**Comment by l8nit3tr0ubl3** [comment]
Im not entirely sure how, but after switching to the debug branch, my code works perfectly lmao. So thank you for your assistance and for putting the time into writting this wrapper in the first place :)

**Comment by l8nit3tr0ubl3** [comment]
Seems to have generateNewAddress missing from the private list :) if you add: 

> def generateNewAddress(self, coin):
        """ Returns private trade history for <pair> """
        return self.__call__('generateNewAddress', {
                             'currency': coin})
itll work fine though :)

**Comment by s4w3d0ff** [comment]
Nice catch! If you don't submit a pull request I'll just make the commit later today or tomorrow. 

I must of spaced and missed this command. [It did make it into the 'PRIVATE_COMMANDS' list](https://github.com/s4w3d0ff/python-poloniex/blob/v0.2.3/poloniex/__init__.py#L58), but I just never wrote the method for it. :roll_eyes:

It should still be possible to call this command using:
```python
polo = Poloniex(key, secret)
polo('generateNewAddress', {'currency': coin})
```
