### ISSUE TITLE
Push API orderbook not receiving all data

### ISSUE THREAD

**Issue by risingsun007** [s4w3d0ff/python-poloniex#79]
When I request orderbook data for a symbol, I appear to be missing data.   Does anyone
else have this problem?  Specifically, I get orderbookremove instructions on data that 
doesn't exist.

**Comment by gcmartinelli** [comment]
Yes, I am also noticing missing data on returnOrderBook. I haven't found the root cause, tho.

**Comment by jknielse** [comment]
I hate to be the bearer of bad news, but to the best of my knowledge this is a known issue with poloniex's push API. They're supposedly going to roll out one that will be more robust, but no official word on when. If you want to maintain a (mostly) accurate view of the orderbook state you'll need to resynchronize the orderbook periodically by using the returnOrderBook endpoint.

It sucks, I know, but it's the best option we've got so far

**Comment by mellertson** [comment]
I have also seen the same thing. I got around it by caching the order book data before beginning to receive order book PUSH updates.  Mine is perhaps a work around, but it might be a good interim solution for you.  

I cache each order book I'm interested in using something like the following:
    

    currency_pairs = ['USDT_BTC', 'BTC_ETH', 'BTC_BTH']
    for currency_pair in currency_pairs:
        pub = PublicApi()
        orderBook = pub.returnOrderBook(currency_pair=currencyPair, depth=depth)
        # store orderBook data in a cache

    # begin receiving order book updates from the PUSH API

And just thinking out loud, you could try re-caching the order book data at perhaps regular intervals.  Or maybe, just re-cache the order book data which is below the depth of an order book update just received by the PUSH API?  It would slow the system down, but at least you'd be guaranteed to have all of the order book data up to the depth of the last received update.

**Comment by s4w3d0ff** [comment]
see #195
