### ISSUE TITLE
extend=True used in examples but doesn't exist in __init__

### ISSUE THREAD

**Issue by ethene** [s4w3d0ff/python-poloniex#84]
Traceback (most recent call last):
  File "loanbot.py", line 156, in <module>
    bot = Loaner(args.config)
  File "loanbot.py", line 21, in __init__
    self.polo = poloniex.Poloniex(config['key'], config['secret'], extend=True)
TypeError: __init__() got an unexpected keyword argument 'extend'

**Comment by s4w3d0ff** [comment]
ugg... ya, sorry #85 fixes most of what is broken from this update, I just need to insert a time converstion function and it should be working...
