### ISSUE TITLE
Why use this API over Poloniex's [Question]

### ISSUE THREAD

**Issue by KaufNation** [s4w3d0ff/python-poloniex#90]
I am looking to write a program for trading on Polo.  Why would you use this wrapper over their supplied python API (https://poloniex.com/support/api/)

**Comment by s4w3d0ff** [comment]
This wrapper is based off of the python wrapper they have listed in the above link:
http://pastebin.com/fbkheaRb

The above wrapper was incomplete so I created this repo in hope to create a more featured wrapper.

In this repo you will find every known API command 'mapped' into the `Poloniex` object. 

This wrapper also has various checks to reduce the amount of bad requests sent to the api, as well as a call limiter (`Coach`) that keeps the wrapper from making calls to poloniex too fast (current call limit is 6 calls per 1 sec).

The only set back is this wrapper uses a 3rd party module `requests`. `requests` has been adopted into python3 core lib, but is still 3rd party for python2. So if you are developing on python2 and your system does not allow installing 3rd party packages, you might not be able to use this module.

**Comment by KaufNation** [comment]
So essentially this wrapper is everything Poloniex's API is plus some?

**Comment by s4w3d0ff** [comment]
Yup, every poloniex api command is accessible via this wrapper, the only thing this wrapper does not wrap is the WAMP push api. I provided basic push api examples in the '[examples](https://github.com/s4w3d0ff/python-poloniex/tree/master/examples)' directory, but I am not too familiar with twisted or asyncio so the examples are very basic, if not 'wrong', (and probably buggy).

I should probably write some pages in the wiki to show how to take advantage of this wrapper...
