### ISSUE TITLE
Get nonce error: poloniex.PoloniexError: Nonce must be greater than 149252340336400. You provided 1492523455181.

### ISSUE THREAD

**Issue by mkuendig** [s4w3d0ff/python-poloniex#97]
Can fix it with changing:

__init__.py

line 118 to: self.coach, self._nonce = coach, int(time() * 100000)

Just add two trailing 00

**Comment by s4w3d0ff** [comment]
I changed it, but its seems like you were using a different wrapper with the same keys?

I was experiencing slow nonces but only by less than 50, yours (149252340336400) seems like it came from a different wrapper. You will most likely need to gen new keys when switching between wrappers.

**Comment by mkuendig** [comment]
Thanks @s4w3d0ff . I just used your API and no wrapper. 

Have created a docker container that has the script below in it:

from poloniex import Poloniex, Coach
import datetime

polo = Poloniex()
myCoach = Coach()

polo.Key = 'keyfrompolo'
polo.Secret = 'secretfrompolo'

polo.public = Poloniex(coach=myCoach)
polo.private = Poloniex(polo.Key, polo.Secret, coach=myCoach)

print (datetime.datetime.now())

balance = polo.private.returnBalances()
print("I have %s ETH" % balance['ETH'])

balance = polo.private.returnBalances()
print("I have %s BTC" % balance['BTC'])

balance = polo.private.returnBalances()
print("I have %s USDT" % balance['USDT'])

That works now. Thanks for fixing it.

**Comment by s4w3d0ff** [comment]
the nonce is changing again. I tested it after using the last nonce change and did not get any errors. If you do get this error again you will probably need to generate and use new api keys. #102

**Comment by poyhugo** [comment]
hey s4w3d0ff  i got a questiosn when i do this:
import requests
r = requests.get('https://poloniex.com/public?command=returnTicker')
r.text

it does not give me the information that i want, i think is because the captcha what do you think?

**Comment by s4w3d0ff** [comment]
maybe, I seem to recall an issue being opened asking about something similar. The user lived in South Asia and their ip location was 'banned' (or requires extra auth, like captcha), probably because of malicious activity from the area, not related to that user. But I think it blocks the api use... I think he submitted a ticket with poloniex and they lifted the ban from his ip. What was the output? Have you tried it with `logging.DEBUG` (to see a bit more info):
```python
import logging
logging.basicConfig()
logging.getLogger('requests').setLevel(logging.DEBUG)
```

**Comment by poyhugo** [comment]
entonces a ti no te pide resolver captchas cada vez que reinicias la pagina?

**Comment by poyhugo** [comment]
The output was 403 code

**Comment by s4w3d0ff** [comment]
Ya this seems really familiar to what was happening to the other user, I would suggest creating a support ticket with poloniex and let them figure it out. It is probably just a security measure that inst configured properly. (Or they had a burst of malicious activity from your general location).

**Comment by skyl** [comment]
My issue that led me here was that I was instantiating the api twice and trying to build a higher level function that was using one instance with one building block and another instance with another. Hope this might help someone else.
